### ISSUE TITLE
Feature: width of toastrs

### ISSUE THREAD

**Issue by zatziky** [diegoddox/react-redux-toastr#101]
Hi Diego,

do you plan to add a customizable width for the toaster? It could fit in the options object as enums `small`, `medium` and `big`.

```
this.toastr.add({
   type: 'success',
   title: 'your title',
   message: 'message',
   options: {
      width: 'small'
  }
  });
```

Cheers, 

Zat

**Comment by diegoddox** [comment]
No, I'm not planing in add this feature but feel free to add and create a `pull request`
