### ISSUE TITLE
Animation side effect

### ISSUE THREAD

**Issue by ilyamkin** [diegoddox/react-redux-toastr#102]
Hi there! 

I'm using your component and found an interesting issue.

First I clicked the close button and fired the `_removeToastr()` event. Then while the toastr box is moving under my mouse (I use `fadeIn` animation), component will run `onleave` and then `onenter` event which make `isHiding = false` and prevent from running `remove(id)`. As a result I see closing toastr, then showing again and then finally closing after 1s.

I propose to remove line `this._setIsHiding(false);` in the `mouseEnter` event, because if we are already hiding we can't cancel our animation and should close anyway.

Thank you!

**Comment by diegoddox** [comment]
Thanks, will look asap.

**Comment by diegoddox** [comment]
If we remove the `this._setIsHiding(false);` from the `mouseEnter` the user will not be able to cancel a animating `toastr` to close, so I've add a `ignoreIsHiding` property.

**Comment by ilyamkin** [comment]
Thanks!
