### ISSUE TITLE
Support of React CSS Modules?

### ISSUE THREAD

**Issue by jerfowler** [diegoddox/react-redux-toastr#103]
How best to get CSS Module support working with toast? 

https://github.com/gajus/react-css-modules

I would like to do something like this:

```javascript
import React from 'react';
import ReduxToastr, { toastr } from 'react-redux-toastr';
import style from 'react-redux-toastr/src/styles/index.scss';
import App from '../../components/App';

const AppWithToastr = props => (
  <div>
    <App {...{ ...props, toastr }} />
    <ReduxToastr position="bottom-right" progressBar className={style['react-toastr']} />
  </div>
);

export default AppWithToastr;


```

**Comment by jerfowler** [comment]
I would also probably change the css class name from `react-toastr` to just `toastr` so we can use dot notation:

```javascript 
<ReduxToastr position="bottom-right" progressBar className={style.toastr} />
```

**Comment by diegoddox** [comment]
I will pass the `className` as `prop` ASAP

**Comment by diegoddox** [comment]
You can pass [className](https://github.com/diegoddox/react-redux-toastr/blob/master/src/ReduxToastr.js#L97) as `prop`
