### ISSUE TITLE
preventDuplicates has no effect. 

### ISSUE THREAD

**Issue by liz-ophiuchus** [diegoddox/react-redux-toastr#105]
It appears that preventDuplicates isn't working. I've diff-ed the incoming and existing toastr, and there is no difference, but the new toastr is appended anyway. Let me know if I can provide any additional info to make debugging easier. :)

**Comment by diegoddox** [comment]
Thanks, will look asap.

**Comment by diegoddox** [comment]
I'm not able to reproduce, you may some difference in your `toastr`, I will close if you're still having this issue fell free to re-open.
