### ISSUE TITLE
Toasts to not disappear if clicked

### ISSUE THREAD

**Issue by kristian-elder** [diegoddox/react-redux-toastr#108]
I cannot reproduce this in the demo, but running against the latest version (4.4.6) in our app - if a toast is clicked, it will never disappear and will also prevent toasts following it from disappearing.

Additionally, while the demo has close buttons on the toasts, I do not get these in my app - is there an option for this?

**Comment by diegoddox** [comment]
what about the `style` have you upgrade as well?

**Comment by kristian-elder** [comment]
Style is imported in project via the npm dependency - so comes from 4.4.6.

**Comment by diegoddox** [comment]
Ok will look asap, and not you don't need to add any option for the close button it shall always be there.

**Comment by kristian-elder** [comment]
A bit more info: This behaviour happens when toasts are created using the actions directly, without going through toastrEmitter. This with the default has no options, which implies removeOnHover: false and showCloseButton: false.

This combination results in the behaviour described - toasts never disappear after clicked.

**Comment by diegoddox** [comment]
Hi @kristian-elder , thanks for the info, I'm a bit busy but asap I will take a look.

**Comment by gytisgreitai** [comment]
I'm having the same problem. On close does not work.

The culprit seems to be `onCSSTransitionEnd` because `ReactTransitionEvents.addEndEventListener` never fires.

I was using `webpack` `css-loader` and importing it via @import scss syntax:

```
:global {
  @import '../node_modules/react-redux-toastr/src/styles/index.scss';
}
```

I i simply include css file in header
```
<link href="http://diegoddox.github.io/react-redux-toastr/4.4/react-redux-toastr.min.css" rel="stylesheet" type="text/css">
```

works fine

**Comment by diegoddox** [comment]
This may be because of the `css` `prefix`, there is no `prefix` on the `scss` files, what browser are you having this issue?

**Comment by gytisgreitai** [comment]
Not sure what you mean? I've tested on latest Chrome

**Comment by diegoddox** [comment]
Never-mind, thanks for the info.

**Comment by lucaong** [comment]
Possibly related to this, on mobile Chrome, tapping on more than one toast causes all but the first of them to never disappear.

A quick look at the code leads me to think that there are two different problems (but I might be off-track):

  1. In the `ToastrBox` component, the events `onMouseEnter` and `onMouseLeave` do not work as expected on a touchscreen: in particular, `onMouseEnter` will trigger when tapping on a toast, and `onMouseLeave` will never trigger. That causes the timeout for the toast disappearance to be canceled on tap, but never be restarted.

  2. There seems to be some shared state between different toasts when it comes to the disappearance timeout, because this issue only occurs when multiple toasts are displayed

**Comment by ilaipi** [comment]
it seems that if I set the `okText` and `cancelText` like this ：
```jsx
const options = {
  okText: 'confirm text',
  cancelText: 'cancel text'
};
<ReduxToastr confirmOptions={options}/>
```
I will not be able to click confirm or cancel btn.

while I create the container without the confirmOptions and set the `okText` and `cancelText` by:
```jsx
const toastrConfirmOptions = {
  ...
  okText: 'confirm text',
  cancelText: 'cancel text'
};

toastr.confirm('Are you sure about that!', toastrConfirmOptions);
```
then I can click the confirm or cancel btn.

**Comment by sereschen** [comment]
Any solution for this? i'm having the exact same issue and use case of @gytisgreitai

**Comment by saidkholov** [comment]
I am having the same issue. Using css modules

**Comment by diegoddox** [comment]
@gytisgreitai can you try import the style via your main`js/jsx`?

**Comment by jalkoby** [comment]
Confirm boxes has been fixed in #114

**Comment by jalkoby** [comment]
Hi guys. I've made  #116 pull request which adds checks for inputed transitions in dev mode. It will help users to figure if something is done wrong

**Comment by amitava82** [comment]
yep css-module seems to be the reason.

**Comment by torkjels** [comment]
I'm also experiencing that the toastrs don't disappear on some mobile devices like the built-in browser on the Samsung Galaxy S4 Android 5.0.1, and the built-in browser on Nexus 7 android 5.1.1. It doesn't disappear when I click the close button or when the timer runs outs. But on Chrome/Firefox it disappears. 

When I click the close button I can see that it's detected by the css (it gets whiter), but nothing else happens. It works like a charm on many mobile devices and all browsers, though!

For whatever it's worth, I'm using the "preventDuplicates", "progressBar" and "timeOut" options.

**Comment by torkjels** [comment]
@gytisgreitai 's solution worked for me as well :)

**Comment by JFGHT** [comment]
In my case, the toastr is not closing automatically if:

- You set the timOut option and you open it for a 2nd time.
- If you don't set the timeOut option but you put the mouse over it.

Using Chrome Version 58.0.3029.110 (64-bit), also happening in FF.

**Comment by tnguven** [comment]
So don't we have any solution to this ???

**Comment by saidkholov** [comment]
@gytisgreitai 's solution is the only workaround I know. @immutablelist

**Comment by justinpincar** [comment]
Hey folks, there's a bug in the processing of the `@keyframes` directive in animation.scss - the animation name is mangled according to preprocessor rules, even though it was wrapped in a :global declaration.

I suggest copying the scss files to your project and importing like this:
```
:global {
  @import './Toaster/styles/index.scss';
}
```

And then change animations.scss for each `@keyframes` directive:
```
- @keyframes fadeIn {
+ @keyframes :global(fadeIn) {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
```

**Comment by iwuvjhdva** [comment]
@justinpincar, thank you so much for the solution that works!

@diegoddox, thank you for the wonderful component, though I think it should be more flexible with custom styling, current approach basically doesn't work with Webpack that is used by the vast majority of users. Guess besides fixing the animations a better approach would be to add extra properties for custom class names, like for example react-tabs project does.
Also there's no way to disable icons globally, I'm setting rrt-left-container's display attribute to none in order to do that.
Hope that was helpful. Thank you again!

**Comment by diegoddox** [comment]
Thanks @iwuvjhdva,
I do agree with you the only issue is that unfortunately, I cannot prioritize this at the moment.

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case anyone feels that this has to be addressed.
