### ISSUE TITLE
If the action creator is used messages without a position are not rendered

### ISSUE THREAD

**Issue by anpieber** [diegoddox/react-redux-toastr#121]
While, according to the documentation, the default location should be used, this is done no where in the code. Therefore, if the actions are not including a position https://github.com/diegoddox/react-redux-toastr/blob/master/src/ReduxToastr.js#74 ```.filter(item => item.position === position)``` simply is false for all sides. I think something like ```item.position ? item.position === position : props.position === position``` instead should fix the problem.

**Comment by diegoddox** [comment]
This should be fixed in the next version.

**Comment by fyodoriv** [comment]
Also had this issue, so far added the position to every action dispatch and it helped. Looking forward to a new version!

**Comment by diegoddox** [comment]
@cbrwizard the next version is available.
