### ISSUE TITLE
Need to add line breaks in toast - \n and <br /> doesn't work. Any way to do this?

### ISSUE THREAD

**Issue by ericlau-solid** [diegoddox/react-redux-toastr#123]
Tried a few things, as described in title, but has no effect.

**Comment by diegoddox** [comment]
If you wanna add line breaks you will have to pass a custom component and in your component you can use [dangerouslySetInnerHTML](https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml)
