### ISSUE TITLE
[Question] Breaking change v6

### ISSUE THREAD

**Issue by NoZiL** [diegoddox/react-redux-toastr#124]
Hi,
Nice work here. I am currently in v5 and I am trying to upgrade to v6. I have trouble finding what are the BCs since my action (ADD) is dispatched but not showed anymore.
Could it be a change in CSS (I have customized it) ?
Cheers

**Comment by diegoddox** [comment]
Hi thanks a lot,
I'm sorry for that but this is because there is a bug on the `BCs`, you need to specify a position else it will not appear and yes you do need to upgrade the `css` if you're not importing directly from the src folder.

**Comment by NoZiL** [comment]
Ok, got it. It is a bug, by passing my position it all works (with small scss overriding).

**Comment by MethodenMann** [comment]
Could you please specify the solution a bit. I also cant see my toastr after upgrading from 5.0.0 to 6.0.0. I have a position set: 
  position="top-left"

**Comment by NoZiL** [comment]
I am using toastr by passing actions, when you build your toastr object, you need to pass the position to it (it's seems that the default position is not used).
e.g:
```
export const toastrSuccessMsg = (title, message) => toastr('success', <Accepted />, title, message)
const toastr = (type, icon, title, message) => ({
  type: type,
  title: title,
  // TODO: check this https://github.com/diegoddox/react-redux-toastr/issues/124#issuecomment-299436123
  position: 'bottom-center',
  ...message && { message },
  options: {
    timeOut: 4000,
    icon: icon,
    showCloseButton: true,
    removeOnHover: true,
  },
})
```

Somewhere in component/container
```
dispatch(toastrActions.add(toastrSuccessMsg('Candidature modifiée')))
``` 

Sorry for close/open...

**Comment by diegoddox** [comment]
The default position should be fixed in the next version
