### ISSUE TITLE
Use a different classname convention

### ISSUE THREAD

**Issue by pablen** [diegoddox/react-redux-toastr#125]
Hello and thanks for such a nice package! I have a minor request.

I've been using the package for around a year and now I updated it and found some new classnames that conflict with my current theme. In particular inside the `.toastr-[position]-container` element I notice new `.title` and `.message` elements with no `toastr-` namespace. I think both `.title` and `.message` classnames are too generic and common and very probably will make the toasts inherit undesired styles from other people base stylesheets or themes.

I know it's possible to override the styles, but as I guess this will be such a common issue, could them (and other possible classnames in the same situation) be updated to be a little more specific? I think changing them to `.toastr-title` and `.toastr-message` would be enough.

Regards.

**Comment by diegoddox** [comment]
Hi @pablen,

Thanks a lot, yes I can du that!

**Comment by JFGHT** [comment]
This is actually critical. I had to modify my CSS in order to avoid conflicts.

**Comment by diegoddox** [comment]
this is fixed.
