### ISSUE TITLE
Redux store path

### ISSUE THREAD

**Issue by JFGHT** [diegoddox/react-redux-toastr#128]
Hello,

I'm starting the installation of react-redux-toastr in a big project and I'm facing a problem: I cannot set the redux toastr reducer path dinamically.

**ReduxToastr.js**:
`toastr: state.toastr ? state.toastr : state.get('toastr')`

I don't want to have toastr in the store's root so, it would be a lot more generic if I were able to decide where should be the toastr located.

Thanks!

**Comment by lagunovsky** [comment]
You can use this method
```
import React from 'react'
import { bindActionCreators } from 'redux'
import { connect } from 'react-redux'
import { ReduxToastr } from 'react-redux-toastr/lib/ReduxToastr'
import * as actions from 'react-redux-toastr/lib/actions'

@connect(
  state => ({ toastr: state.getIn(['costom', 'path']) }),
  dispatch => bindActionCreators(actions, dispatch),
)
export default class Toastr extends React.Component {
  render() {
    return (
      <ReduxToastr {...this.props} />
    )
  }
}
```

**Comment by diegoddox** [comment]
will close but feel free to re-open in case you need.

**Comment by TheSharpieOne** [comment]
In my case, I am using `redux-optimistic-ui` which wraps the state in stuff to track optimistic updates in case it needs to revert them.
This meant that `toastr` was not on the root state which lead me here.
@lagun4ik's example helped solve my issue.
I simplified it as to not need to create another component in the middle:
```jsx
import { ensureState } from 'redux-optimistic-ui';
import { connect } from 'react-redux';
import { ReduxToastr } from 'react-redux-toastr/lib/ReduxToastr';
import * as actions from 'react-redux-toastr/lib/actions';
import 'react-redux-toastr/lib/css/react-redux-toastr.min.css';

// Since we are using redux-optimistic-ui which wraps the state, we have to unwrap the state for react-redux-toastr.
export default connect(
  state => ({ toastr: ensureState(state).toastr }),
  actions
)(ReduxToastr);
```
