### ISSUE TITLE
Not implementing standard toast messages

### ISSUE THREAD

**Issue by NullDivision** [diegoddox/react-redux-toastr#13]
I tried using it but it looks like a lot of the styles are not properly implemented and I can't actually remove the close button. The documentation is scarce and there are very few options to be had.

**Comment by diegoddox** [comment]
To be honest I don't have updated the demo page for a while. 
Can you please give me more info about the close button issue?
about the docs as you know this is a open-source project so feel free to change anything and make a pull-request.

**Comment by khanghoang** [comment]
@diegoddox I want to help your work, let me know if you need any help from me.

**Comment by diegoddox** [comment]
@khanghoang thanks a lot!

**Comment by diegoddox** [comment]
@NullDivision I will close the issue but feel free to re-open when you're able to provide more info about it.
