### ISSUE TITLE
Ability to override global preventDuplicates

### ISSUE THREAD

**Issue by rachitbhasin** [diegoddox/react-redux-toastr#130]
**Issue:** When the options provided to the ReduxToastr include `preventDuplicates: true` , even though the options provided to the toastr while initiating a toastr has been provided options to have `preventDuplicates: false` it doesn't override the global setting.

**Example:** Global configuration in ReduxToastr  is set to  preventDuplicates: true
```
import ReduxToastr from 'react-redux-toastr'

<ReduxToastr
      preventDuplicates={true} />
```

While firing the toastr override the preventDuplicates:
```
import {toastr} from 'react-redux-toastr';

toastr.info('Info!!!', message, {preventDuplicates: false});
```

**Actual result:** The preventDuplicates property in the  options passed to the eventemitter doesn't override the global configuration and allow duplicate for certain events.

**Expected result:** The preventDuplicates property  in the  options passed to the eventemitter should override the global configuration and allow duplicates for some events.

**Comment by diegoddox** [comment]
Hi @rachitbhasin , We don't have `preventDuplicates` as a `toastr` option but I will add as a request.

**Comment by rachitbhasin** [comment]
@diegoddox I have created a PR for this feature. Please review.
#132
