### ISSUE TITLE
Delay when using custom icons.

### ISSUE THREAD

**Issue by sjain-mi9** [diegoddox/react-redux-toastr#131]
Not sure if it is a bug or I'm using it wrong, but whenever I use a custom icon, the toast appears after around couple of seconds of delay. Is there a way to use our own icons at global level or we need to add that for each page?

**Comment by diegoddox** [comment]
For sure this is not a bug, it can depend on how you're importing/adding these icons to your application and no there is no way to add custom fonts to the module at the moment

**Comment by diegoddox** [comment]
I will close but feel free to re-open in case you have further questions.
