### ISSUE TITLE
The position prop isn't working

### ISSUE THREAD

**Issue by thedrew12** [diegoddox/react-redux-toastr#134]
```
          <ReduxToastr
            timeOut={7000}
            newestOnTop
            position="bottom-left"
            transitionIn="bounceIn"
            transitionOut="bounceOut"
          />
```
I can't move the position of the Toastr, I've tried a different position, but it is always in the top left position, am I missing something? I've tried passing it in as a config option when calling the function, but that doesn't work. The rest of the props are working, transition, timeOut, etc...

**Comment by diegoddox** [comment]
Hi @thedrew12, You're doing right I will take a look ASAP, thank you!

**Comment by khushi511** [comment]
Facing Same Issue. Can you resolve It ASAP?

**Comment by diegoddox** [comment]
I'm not sure when but I will take a look.

**Comment by justsudheerpaliwal** [comment]
@thedrew12 @khushi511 might have to do something with the included css. Have you correctly imported them?

**Comment by diegoddox** [comment]
Are you guys still facing this issue?

**Comment by thedrew12** [comment]
Seems to be working for me now in a different project so I think its fine.
