### ISSUE TITLE
Dispatching the toastr actions directly prevents timeout from working

### ISSUE THREAD

**Issue by neocolmartin** [diegoddox/react-redux-toastr#135]
I have a Redux action that (using `redux-thunk`) displays a toastr success notification after completing some ofther async work:

```
import { actions as toastrActions } from 'react-redux-toastr';

export function send() {
  return dispatch => {
    // ...
    dispatch(toastrActions.add({
      type: 'success',
      title: 'Success',
      message: 'Your information has been submitted',
      timeout: 4000,
    }));
    // ...
  };
}
```

(The reason I want to do it this way is so I can keep all my logic for the "send" action together, where I can fairly easily unit test it - I only need to mock the async parts of the action and use `redux-mock-store` to check which actions such as `toastrActions.add` were dispatched.)

However, these are slightly different from the notifications displayed when using the emitter:
* The notifications do not time out and disappear on their own, and
* There is no close button on them.

Is there any way to dispatch the actions directly and get the same behaviour as when using the emitter?

**Comment by VincentN** [comment]
@diegoddox, do you have any pointers for us for this use case? I hope you can find some time, next to every other day-to-day thing to do, to take a look. :-) Your work is very much appreciated!

**Comment by IvanCoronado** [comment]
I have same problem here... but when I dispatch the same action twice

@neocolmartin If you need a workaround I fixed it by now with:
`
import { bindActionCreators } from 'redux';
import { actions as toastrActions } from 'react-redux-toastr';

export function send() {
  return dispatch => {
    const toastr = bindActionCreators(toastrActions, dispatch);

    toastr.add({
      id: 'INFORMATION_SUBMITTED',
      type: 'success',
      title: 'Success',
      message: 'Your information has been submitted',
      timeout: 4000,
    });
    setTimeout(() => { toastr.remove('INFORMATION_SUBMITTED'); }, 3500);
  };
}
`

**Comment by JFGHT** [comment]
Same here. Having this issue after a 2nd dispatch.

**Comment by GustavoMantuan** [comment]
@neocolmartin  Dont know if your problem got resolved, but in my situation I made this:

```
...fetch things)
.catch(function (error) {
            dispatch(toastrActions.add({
                id: `erro_${error.statusCode}`,
                type: 'error',
                title: "Error",
                position: 'top-right'.
                attention: true,
                message: error.message,
                options: {
                    showCloseButton:true
                }
```

Then in my high order component, 

```
 <ReduxToastr
                    timeOut={3000}
                    newestOnTop={true}
                    preventDuplicates
                    position="top-right"
                    transitionIn="bounceIn"
                    transitionOut="bounceOut"
                    progressBar/>
```

**Comment by Nantris** [comment]
@GustavoMantuan can you elaborate on your solution? I'm not quite sure what your solution is but I sure would like to be able to dispatch actions directly.

**Comment by Nantris** [comment]
A viable solution to this seems to be to simply ditch the `progressBar` attribute if you don't need it. The error seems to be related to `progressBar` requiring a duration/timeout (I forget the exact wording.)

EDIT: This doesn't seem to work consistently unfortunately.

**Comment by diegoddox** [comment]
Please follow this one now #173

**Comment by JoshMcCullough** [comment]
FYI I guess it's `timeOut` instead of `timeout` (different cases are used in the comments within this issue). But neither option seems to work for me ... ?

**Comment by Nantris** [comment]
Hope this helps someone. You need to use `timeOut` (note capitalization) AND you need to pass it under the `options` property.


```js
dispatch(
  toastrActions.add({
    options: {
      timeOut: 2500,
    },
  })
);
```
