### ISSUE TITLE
Using animate.css from https://daneden.github.io/animate.css/ for animations?

### ISSUE THREAD

**Issue by ckpinguin** [diegoddox/react-redux-toastr#137]
I have made a rudimentary test by pasting all your css together with animate.css and it seems to work out partially (so far I only tried `hinge` for the `transitionOut` for coolness sake).
I'm not good at SASS/SCSS, so you might give it a try and integrate those animations into your styles?

And THANKS for making this really nice toaster component. It is a breeze to use it with Redux and making my thesis more fun :-)

GOD bless you.

Chris

**Comment by diegoddox** [comment]
Hi @ckpinguin thanks,
you don't need to include all the styles in the `animate.css` file, you can just include it in your project and it will work.
