### ISSUE TITLE
Mouse enter should not delay an explicit close click

### ISSUE THREAD

**Issue by torkjels** [diegoddox/react-redux-toastr#138]
I posted an issue in November about `mouse enter` canceling close after you've clicked the X (https://github.com/diegoddox/react-redux-toastr/issues/76). It got more or less fixed in this commit (https://github.com/dcmdestello/react-redux-toastr/commit/a06bd5eb2f2b29e60f17e04a3cc438981c1d63ad), but I still feel the behavior is very annoying, and our users tend to complain about it.

What happpens is: If you click on the close, the toastr starts to shrink. The problem arises if you then decide to move your mouse which, if the toastr is on the right side of the screen, usually means you move your mouse across the toastr. This causes a mouse enter event, delaying the toastr from closing.
This makes users think that something went wrong and that they have to close the toastr again. And again and again and again if the same thing happens every time they try to close.

I've experienced this quite a few times as well, and it's annoying to say the least.

In my opinion there is no need to delay the close on mouse enter if you've **explicitly** clicked the close button.

**Comment by diegoddox** [comment]
Hi @torkjels thanks and yes it can be very irritated this kind of behavior, not sure when but will look asap

**Comment by VincentN** [comment]
Noticed this too, thanks for taking a look @diegoddox!

**Comment by rajsek** [comment]
we also face the same issue.
When will be the issue get fix?

**Comment by diegoddox** [comment]
I do not have time this year, maybe you could give me a hand ;)

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case anyone feels that this has to be addressed.
