### ISSUE TITLE
IE10 Support

### ISSUE THREAD

**Issue by ro-savage** [diegoddox/react-redux-toastr#14]
First up, awesome toast, we are loving it.

I am using it on our site that requires IE10 support. Unfortunately `Map` isn't support by IE10 and `Map` [can't be polyfilled / shimmed](https://github.com/eriwen/es6-map-shim).

I have forked the repo and changed `Map` to a regular `Object`.

Feel free to accept PR if you'd like to support IE10, or suggest another way of handling IE10 :)

**Comment by diegoddox** [comment]
@ro-savage 
Thanks for your feedback happy to know that you like it and thanks for your contribution.
