### ISSUE TITLE
Custom component for confirm box

### ISSUE THREAD

**Issue by rzueger** [diegoddox/react-redux-toastr#140]
We need the ability to render a custom component in a confirm box instead of a simple text message (like this is already possible in the normal toastr box). In our specific case, we have to be able to render a title and there could be line breaks in the message.

Example:

```
options.component = () => (
  <div>
    <div className="title">{title}</div>
    <div className="message">
      {message.split('\n').map((item, key) => <span key={key}>{item}<br/></span>)}
    </div>
  </div>
)
```

We could add this new `component` prop for the confirm box and submit a pull request, if you're interested in this feature, too. Thoughts?

**Comment by diegoddox** [comment]
Hi @rzueger thanks, you're very welcome to create a pull request.
