### ISSUE TITLE
Add support for transitionIn="bounceInUp" transitionOut="bounceOutDown"

### ISSUE THREAD

**Issue by slaweet** [diegoddox/react-redux-toastr#146]
Currently supported`transitionIn="bounceInDown"  transitionOut="bounceOutUp"` work well for `position="top-*"` but looks weird for `position="bottom-*"` as it slides over the whole screen instead of just from the closer bottom edge of the screen.

**Comment by diegoddox** [comment]
Hi @slaweet thanks, I'll take a look.

**Comment by diegoddox** [comment]
Hi, will close but feel free to re-open in case you really think this feature is necessary, you're more than welcome to give me a hand and create a PR for it if you can <3
