### ISSUE TITLE
Size Prop - Error

### ISSUE THREAD

**Issue by abdalla** [diegoddox/react-redux-toastr#147]
I'm getting the error below:
Warning: Failed prop type: Invalid prop `size` of type `number` supplied to `ReduxToastrIcon`, expected `string`.
    in ReduxToastrIcon (created by ToastrBox)
    in ToastrBox (created by ReduxToastr)
    in span (created by ReduxToastr)
    in div (created by ReduxToastr)
    in span (created by ReduxToastr)
    in span (created by ReduxToastr)
    in ReduxToastr (created by Connect(ReduxToastr))
    in Connect(ReduxToastr) (at index.js:25)
    in div (at index.js:23)
    in Router (at index.js:22)
    in Provider (at index.js:21)
<img width="1520" alt="screenshot 2017-07-12 21 28 57" src="https://user-images.githubusercontent.com/373499/28146611-23713678-6749-11e7-9810-5732ae44d61f.png">

**Comment by diegoddox** [comment]
You're using `typescript` I'm not the one that is updating the `types`.

**Comment by abdalla** [comment]
Nops..

I'm using React + vanillajs.

I could noticed that the value there is 32, I believe it can be easily fixed putting it in a quote. But I'm not sure what it will impact.

Thank you for the answer!

**Comment by diegoddox** [comment]
Ok will look asap.

**Comment by abdalla** [comment]
Closing this issue, I figured out what was happening and definitely the problem was not with the toastr.

**Comment by diegoddox** [comment]
Thanks!
