### ISSUE TITLE
Module not found to style

### ISSUE THREAD

**Issue by gabrielferreiraa** [diegoddox/react-redux-toastr#152]
[ERROR]  Module not found: Error: Can't resolve 'modules/react-redux-toastr/lib/css/react-redux-toastr.min.css' 

In my code:
`import 'modules/react-redux-toastr/lib/css/react-redux-toastr.min.css'`

just `modules` because I have alias webpack, but dont work with `/node_modules/` too

Why ? Not understand

**Comment by diegoddox** [comment]
You may wanna use `require` when importing from `node_modules`
ex: `require('!style!css!react-redux-toastr/lib/css/react-redux-toastr.min.css')`

**Comment by gabrielferreiraa** [comment]
Change error !!
![error](https://user-images.githubusercontent.com/17201177/28935893-515bb9e0-785c-11e7-9362-cd4adc751d05.png)

**Comment by diegoddox** [comment]
`require('!style-loader!css-loader!react-redux-toastr/lib/css/react-redux-toastr.min.css')`

**Comment by diegoddox** [comment]
Works for you?

**Comment by diegoddox** [comment]
I will close but feel free to re-open if necessary.

**Comment by gabrielferreiraa** [comment]
Yaaaa, success :D Thx!!
