### ISSUE TITLE
TransitionOut stopped working for version 7.1.1

### ISSUE THREAD

**Issue by socrat3z** [diegoddox/react-redux-toastr#154]
While using 7.1.1 when toast going to close an error occurs. Seems to have some problem with TransitionGroup.
Version 7.0.0 works as expected.

**Comment by soapnrope** [comment]
![image](https://user-images.githubusercontent.com/6512443/28930407-8bb68d3a-787b-11e7-93bc-2a910facea16.png)

This is the error I get with 7.1.1. Downgrading to 7.1.0 fixes the issue. Frankly issue started when I upgraded something in my package.json file, but sadly I'm unable to trace which packages breaks this one(if thats even a case)

**Comment by diegoddox** [comment]
@socrat3z and @soapnrope thanks will look asap!

**Comment by vanhonit** [comment]
I just found you use addEndEventListener and removeEndEventListener from react/lib/ReactTrasitionEvent but in the CSSTransitionGroup didn't have that event.

**Comment by shengnian** [comment]
+1

**Comment by diegoddox** [comment]
This should be fixed in the latest.

**Comment by Geczy** [comment]
When can this be released (versioned)? 

EDIT: Receiving this issue in 7.1.3 still 

`[react-redux-toastr] The toastr box was closed automatically, please check 'transitionOut' prop value`
