### ISSUE TITLE
"please check 'transitionOut' prop value"

### ISSUE THREAD

**Issue by Geczy** [diegoddox/react-redux-toastr#156]
`[react-redux-toastr] The toastr box was closed automatically, please check 'transitionOut' prop value`

Using 7.1.3

Using toastr.confirm(), clicking OK or Cancel shows this message. Same with any .success() etc events

Clicking OK on the modal, removes the dialog, but keeps the backdrop for 4 seconds or so, then removes it and shows this warning in console

**Comment by diegoddox** [comment]
Are you using a custom CSS class for the `transitionOut `?

**Comment by Geczy** [comment]
I'm not. I'm using default props

```js
      <ReduxToastr
        position="bottom-center"
        progressBar
        preventDuplicates
      />
```

I also tried adding the default props to it like in the readme and it didn't fix anything

```
      transitionIn="fadeIn"
      transitionOut="fadeOut"
```

**Comment by diegoddox** [comment]
Thanks @Geczy, I will look asap!

**Comment by vagonzalez** [comment]
Same issue

**Comment by dmurawsky** [comment]
Same here, my settings were:
```
<ReduxToastr
    timeOut={40000}
    preventDuplicates
    position="bottom-left"
    transitionIn="fadeIn"
    transitionOut="fadeOut"
/>
```

**Comment by dmurawsky** [comment]
Looks like, for me, it was caused by the [`maxAnimationDelay` ](https://github.com/diegoddox/react-redux-toastr/blob/2662ac8c5ef4c4e055d4dd0594c1bd1afbd33939/src/config.js) in the [`onCSSTransitionEnd `](https://github.com/diegoddox/react-redux-toastr/blob/2662ac8c5ef4c4e055d4dd0594c1bd1afbd33939/src/utils.js#L98-L105) util function

**Comment by Geczy** [comment]
How so?

**Comment by dmurawsky** [comment]
Did you look at the code @Geczy?

**Comment by diegoddox** [comment]
My bad guys, I was using `transitioned` instead of `animationend`.

**Comment by zeeshan09** [comment]
I'm using the latest version of react-redux-toastr, I'm still getting the error and toastr is not being displayed.

`<ReduxToastr
      timeOut={6000}
      newestOnTop={true}
      preventDuplicates
      position="top-right"
      transitionIn="fadeIn"
      transitionOut="fadeOut"
      progressBar
   />`

**Comment by echarles** [comment]
Same error here. Probably due to local env? Anyone got a fix?

**Comment by tomiadebanjo** [comment]
I'm still having this issue

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case anyone feels that this has to be addressed.

**Comment by yosrimhamdi** [comment]
I am getting the same warning in 2021. Please resolve this issue
