### ISSUE TITLE
Option to extend or replace the ReduxToastr options

### ISSUE THREAD

**Issue by torkjels** [diegoddox/react-redux-toastr#159]
This isn't a bug as much as it is a feature request.

When I set the toastr settings in the app root like such:

```
<Provider store={store}>
   <div style={{ height: '100%' }}>
      <Router history={history} children={routes} />
      <ReduxToastr
        progressBar
        timeOut={2000}
        transitionIn='fadeIn'
        transitionOut='fadeOut'
        preventDuplicates />
    </div>
</Provider>
```
The options set here in ReduxToastr are _replaced_ rather than _extended_ in the toastr.confirm function.
In the confirm function (toastrEmitter.js lines 45-50)
```
actions.confirm = function () {
  emitter.emit('toastr/confirm', {
    message: arguments.length <= 0 ? undefined : arguments[0],
    options: (arguments.length <= 1 ? undefined : arguments[1]) || {}
  });
};
```
you can see that the arguments are either none (undefined), or the ones passed to the confirm function itself. The "global" functions set in the ReduxToastr component are discarded.

So if I want the confirm transitionIn and transitionOut to be different from the library's default, I need to include transitionIn and transitionOut in the options object of every toastr.confirm() call.

It would be nice if the toastr.confirm made it possible to choose to either extend or replace the already set "global" options of the ReduxToastr component. Or that it extends the already set options by default, but that would possibly be somewhat of a breaking change.

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case anyone feels that this has to be addressed.
