### ISSUE TITLE
toastr continue fire after action destroy run

### ISSUE THREAD

**Issue by khoaanh2212** [diegoddox/react-redux-toastr#160]
I have a page login use redux saga,when i login failed,i run a toaster error,and after that i saw redux run action destroy toastr,but after that,when i login success and push to dashboard page,toastr continue show the toastr error which one is destroyed.
```javascript
export function* authCall(action) {
  const { email, password, rememberMe, locale, formatMessage } = action;
  try {
    yield put(actionOnLoad());
    yield put(showLoading());

    const url = `${config.api.url}/auth/login`;
    const options = postOptionsWithoutToken(
      {
        email,
        password,
        rememberMe,
        instanceSubDomain: config.api.instanceSubDomain,
      }, locale);
    const result = yield call(request, url, options);
    yield put(actionLoadSuccess());
    yield put(hideLoading());
    yield put(actionAuthSuccess(result.data));
    yield put(push('/'));
    yield put(changeLocale(result.data.user_data.language));
  } catch (err) {
    yield put(hideLoading());
    const errResponse = yield err.response.json();
    const errorCode = errResponse.statusCode ? errResponse.statusCode : err.message;
    yield put(actionLoadSuccess());
    toastr.error('Error', formatMessage(messages[errorCode]));
  }
}
```

**Comment by diegoddox** [comment]
I will not recommend using the `toastr` in your `generator function`, why you don't add the `toastr.error` on the `login-view`?

**Comment by khoaanh2212** [comment]
I tried with `toastr.error` on the `login-view` not in the `generator function` but the error are the same

**Comment by diegoddox** [comment]
Okay thanks, will take a look asap.

**Comment by diegoddox** [comment]
Take a look at [this](https://github.com/gaearon/redux-devtools/issues/304#issuecomment-251715413) issue and see if is related.

**Comment by diegoddox** [comment]
Take a look at this #109 issue.

**Comment by khoaanh2212** [comment]
@diegoddox thanks,it works well.
