### ISSUE TITLE
Version in Git different than NPM ?!

### ISSUE THREAD

**Issue by paulincai** [diegoddox/react-redux-toastr#166]
The package.json of 7.1.5 has the following dependencies:
`"peerDependencies": {
    "react": "^0.14 || ^15.0.1",
    "react-redux": "^4.0.1 || ^5.0.1",
    "redux": "^3.0.5"
  }`

No react ^16.0.0 mentioned in the NPM.

Console shows: **npm WARN react-redux-toastr@7.1.5 requires a peer of react@^0.14 || ^15.0.1 but none was installed.**

**Comment by diegoddox** [comment]
Thanks, fixed in the next v
