### ISSUE TITLE
Styling Toastr

### ISSUE THREAD

**Issue by danmo** [diegoddox/react-redux-toastr#167]
Hi, is there any way for dynamically changing styles of a specific toast message.

In some cases I have a huge text to display which sadly overflows. Only for some messages I would like to  add more css styling such as greater width.

**Comment by danmo** [comment]
For whoever needs something like this, for now the simplest solution was to pass it a custom component,on didMound/willUnmount callbacks lookup the parent and set custom styling/remove custom styling.

```
class CustomLocalizedToastr extends Component {
  componentDidMount() {
    const topCenterNode = this.findAcestor(this.node);

    topCenterNode.style.width = '550px';
  }

  componentWillUnmount() {
    const topCenterNode = this.findAcestor(this.node);

    topCenterNode.style.width = '350px'; // it's initial value so we don't affect other messages
  }

  findAcestor(_el) {
    let el = _el.parentNode;
    while (el) {
      if (el.classList.contains('top-center')) {
        return el;
      }

      el = el.parentNode;
    }

    return null;
  }

  render() {
    return (
      <div ref={node => { this.node = node; }}>
        <Text> Some notification text goes here....</Text>
      </div>
    );
  }
}
```
```
    toastr.warning('', {
      component: CustomLocalizedToastr,
      attention: true,
      timeOut: 10000,
    });
```

**Comment by diegoddox** [comment]
Have you tried the `message` method? this one you can use in case you need to display a huge amount of text

**Comment by diegoddox** [comment]
will close but feel free to re-open in case u needed.

**Comment by mkhoussid** [comment]
For anyone else coming here, this didn't work for me, so I just ended up doing,
```
.redux-toastr .bottom-right {
    width: 600px;
}
```
in any css file that is imported by your app.
