### ISSUE TITLE
Use display flex in place of floats

### ISSUE THREAD

**Issue by copycut** [diegoddox/react-redux-toastr#168]
# Use display flex in place of floats

That will allow you to center vertically the content independently of the content size.

https://github.com/diegoddox/react-redux-toastr/blob/d41d5c37ff583a3c823d7257f7710404e1ba400c/src/styles/index.scss#L126

<img width="384" alt="screen shot 2017-11-28 at 11 23 24" src="https://user-images.githubusercontent.com/612718/33315270-85b16f52-d430-11e7-910a-bbf4ad69b6f6.png">

**Comment by diegoddox** [comment]
Thanks @copycut , maybe you can give me a hand on that ;) PR's are very welcome

**Comment by diegoddox** [comment]
will close but fill free to make a pr if you wanna it ;)
