### ISSUE TITLE
cdnjs hosting

### ISSUE THREAD

**Issue by sashberd** [diegoddox/react-redux-toastr#169]
Hi @diegoddox
We would like to [host ](https://github.com/cdnjs/cdnjs/issues/10642)you library on cdnjs
What files we should add?

**Comment by diegoddox** [comment]
This is not possible at the moment, the build folder is not included in the repo.

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case you feel that this has to be addressed.
