### ISSUE TITLE
Missing lib folder - NPM v2.2.2 & v3.0.2 Broken

### ISSUE THREAD

**Issue by ro-savage** [diegoddox/react-redux-toastr#17]
Version v2.2.2 & v3.0.2 are missing the lib folder. Maybe added to NPM without doing a build first?

**Comment by diegoddox** [comment]
@ro-savage 
Strange as I do have build! and the lib folder as well, do you have any idea why this is happen?

**Comment by diegoddox** [comment]
@ro-savage I was smart enough to remove the lib option from the package.json, but now is fixed.

**Comment by diegoddox** [comment]
@ro-savage thanks a lot, I have deprecated these version as well

**Comment by ro-savage** [comment]
No worries. Thank for fixing it up so quickly :)
