### ISSUE TITLE
attention shadow click

### ISSUE THREAD

**Issue by MethodenMann** [diegoddox/react-redux-toastr#170]
To show a toastr that should prevent the user from doing anything else as long as the task is in progress (toastr is shown) we use the attention property. By default, a click on the shadow removes the toastr. We like to enhance redux-toastr to prevent this so that the toastr is kind of blocking.

proposal: function property `onAttentionClick` (or onShadowClick, onBackgroundClick?) that by default calls remove(item.id) but let you override this behavior.

 I would be happy to contribute this change. what do you think?

**Comment by diegoddox** [comment]
Spunds great, you are more than welcome!
