### ISSUE TITLE
Different behaviour when use `actions.add()` and `toastr.success()`

### ISSUE THREAD

**Issue by eugeneglova** [diegoddox/react-redux-toastr#173]
**The problem:**
When I use `actions` instead of regular `toastr` I can't use default options which automatically added here
https://github.com/diegoddox/react-redux-toastr/blob/master/src/toastrEmitter.js#L5
https://github.com/diegoddox/react-redux-toastr/blob/master/src/utils.js#L65

and in this case I lost some features like creating timeout again when mouse leave here
https://github.com/diegoddox/react-redux-toastr/blob/master/src/ToastrBox.js#L112-L122

you may notice that when I use `actions.add()` I have to set all defaults myself because function `add` just forwards payload to action 
https://github.com/diegoddox/react-redux-toastr/blob/master/src/actions.js#L25

As a result I can't use any of default options on actions.

So I'd suggest you to add some function which add default values for it before forward it to action creator.

here is an example I used for demo

![image](https://user-images.githubusercontent.com/2828226/34471359-7236ecca-ef58-11e7-9820-5e19a62cfeb6.png)

![demo](https://user-images.githubusercontent.com/2828226/34471351-40f74ca4-ef58-11e7-834a-22d0f159895f.gif)

**Comment by jayfunk** [comment]
Agreed. It appears when using the actions form of add some options are ignored:
```    
this.props.add({
      type: 'error',
      title: 'Test Title',
      message: 'Hello ICON!',
      options: {
        timeOut: 0,
        position: 'top-right',
        icon: <i className="material-icons">place</i>,
        component: <TestComponent />,
      },
    });
```

In this case position is ignored when placed inside the `options` field where if moved up to the root of the configuration it is now read. The docs do not outline what the expected API is for an action object vs the `toastr.add` call.

**Comment by diegoddox** [comment]
Thanks @eugeneglova, this is more or less related to #135 and the issue may be because the actions are not using the same [helper](https://github.com/diegoddox/react-redux-toastr/blob/master/src/utils.js#L53) function as the `toastr.emitter`

**Comment by frankrod** [comment]
what was the solution for this? 
I'm having the same issue I looked at #135 and see no solution either.

**Comment by diegoddox** [comment]
Hi @frankrod I didn't have the time to fix yet

**Comment by diegoddox** [comment]
do it to inactivity, will close.
