### ISSUE TITLE
Add links on message

### ISSUE THREAD

**Issue by aranchafoz** [diegoddox/react-redux-toastr#176]
Hi, 
I'm trying to add some links, that redirect to another url of my application, inside toast message.
For that I use component prop of toastOptions:

![captura de pantalla 2018-02-05 a las 15 53 58](https://user-images.githubusercontent.com/14368971/35810699-e298e208-0a8c-11e8-8133-0bfca539b5ff.png)

For the development of my app I'm using React-Router, React-Bootstrap and React-Router-Bootstrap (`<LinkContainer>`). So I need component `<LinkContainer>` for go to a specific route in my app, but when I place this component inside a toast message and click on the rendered link, I found this error:

![captura de pantalla 2018-02-05 a las 15 59 49](https://user-images.githubusercontent.com/14368971/35811008-bcecb948-0a8d-11e8-8316-292434465a47.png)
![captura de pantalla 2018-02-05 a las 16 00 21](https://user-images.githubusercontent.com/14368971/35811009-bd114178-0a8d-11e8-895e-88bdee571cd7.png)

Actually, there's some logic for that error because `<ReduxToastr>` is not a children of `<Router>`. But I don't know how to solve this.

There is any way of integrate react-router with react-redux-toastr for add links inside the message???

**Comment by diegoddox** [comment]
Hi @aranchafoz, sorry but at the moment is not possible to pass props.

**Comment by atlanteh** [comment]
Actually your problem is that your toaster is placed outside your router. If you place it inside your router it should work.
