### ISSUE TITLE
Cannot read property 'confirm' of undefined

### ISSUE THREAD

**Issue by pepesenaris** [diegoddox/react-redux-toastr#18]
I have the following in App.js

```
<Provider store={store}>
        <div>
          <ReduxToastr />
          <Router history={hashHistory}>
            <Route path='/admin' component={Comp1}>
              {/* some components here*/}
            </Route>
            <Route path="/" component={Comp2}>
            {/* some components here*/}
          </Router>
        </div>
      </Provider>
```

I can not even start the app because I keep getting a "Cannot read property 'confirm' of undefined" error from the ReduxToastr component

**Comment by diegoddox** [comment]
@pepesenaris have you add the `toastr` `reducer`?

```
import {reducer as toastrReducer} from './toastr';
export default combineReducers({
  // others...
  toastr: toastrReducer
});

```

**Comment by pepesenaris** [comment]
@diegoddox Yes, I did, which is why I do not understand what is happening..

I'll put the relevant snippets of code related to toastr that I'm using.

```
import { combineReducers } from 'redux-immutablejs'
import { reducer as toastrReducer } from 'react-redux-toastr'

const rootReducer = combineReducers({
  toastr: toastrReducer,
//... others reducers from my app here
})
export default rootReducer
```

In a react component:

```
import { toastr } from 'react-redux-toastr'
class Foo extends Component {
 confirmDelete(warningText, id){
    const confirmOptions = {
      onOk: () => {console.log("Deleted")},
      onCancel: () => {console.log("Canceled delete of ", id)}
    }
    toastr.confirm(warningText, confirmOptions)
    this.props.actions.deleteNodeRequest(id)
  }

render() {
// render code...
}
}
```

When I remove the ReduxToastr component from App, the error goes away of course, yet the toastr reducer is properly mounted... so that's why it's giving me headaches
![Screenshot from devtools reducers](https://cloud.githubusercontent.com/assets/7563228/14360568/6a0fbd12-fccd-11e5-99b9-fc11e8ed9506.png)
Cheers

**Comment by diegoddox** [comment]
@pepesenaris strange! I have just publish a new version where it will not crash the app if there is no `toastr` `reducer`, can u please upgrade and console.log the `toastr` object?

**Comment by pepesenaris** [comment]
Ok, @diegoddox , I'll give it a try and let you know. Thanks

**Comment by pepesenaris** [comment]
Now, the app does not crash.
The toastr/ADD action is fired and the toastrs array updated accordingly but the message never shows up. Really odd

**Comment by diegoddox** [comment]
@pepesenaris what are you using as a dev-server?

**Comment by pepesenaris** [comment]
@diegoddox I'm using webpack, configured according to the setup given by [nwb](https://github.com/insin/nwb)

**Comment by diegoddox** [comment]
@pepesenaris I will assume that you have include the css style?

**Comment by pepesenaris** [comment]
I have it on the head tag, in the index.html... it's loading properly

**Comment by diegoddox** [comment]
@pepesenaris very strange! my last opinion will be that you remove the `node_modules` reinstall and clean your browser cache!

**Comment by pepesenaris** [comment]
I'll check that. endeed very rare. 
I'm looking into the inspector and the redux-toastr div has height 0.... is that normal?

**Comment by diegoddox** [comment]
That should not be the problem.

**Comment by diegoddox** [comment]
@pepesenaris  what is the css version you are using? you will need to upgrade as well

**Comment by pepesenaris** [comment]
version 3.0.0 of the css

**Comment by diegoddox** [comment]
@pepesenaris you should not have `height` `0` in v3.0.0
http://diegoddox.github.io/react-redux-toastr/3.0.0/react-redux-toastr.css

**Comment by pepesenaris** [comment]
I'm out of ideas... Maybe it has something to do with using immutablejs.

**Comment by diegoddox** [comment]
@pepesenaris  I don't think that should be any problem!

**Comment by diegoddox** [comment]
@pepesenaris can you provide a copy of the project but with all your private code removed?

**Comment by pepesenaris** [comment]
@diegoddox not right now :-(. I'll give it a try later, Thanks anyway

**Comment by diegoddox** [comment]
@pepesenaris np

**Comment by nicomfe** [comment]
Im having the exact same problem.
Using { combineReducers } from 'redux-immutablejs' as well

I can see the action being fired on the console:
 action @ 14:14:41.705 @ReduxToastr/toastr/ADD 

Store is updated accordingly but message doesnt show up :(

EDIT: I found the problem, it is actually related with immutable 
In the following lines, in the file ReduxToastr.js

```
@connect(state => ({
  toastr: state.toastr
})
```

At that point state is gonna be an immutable object, so state.toastr will return undefined, unleast we do:

```
@connect(state => ({
  toastr: state.get('toastr')
})
```

Not sure what the best way to solve this is tho, any thoughts?

**Comment by nicomfe** [comment]
I created a pull request #20 with a not that fancy solution, but solves the problem of immutable states

**Comment by diegoddox** [comment]
@nicomfe thanks and sorry for the late reply.

**Comment by jchapelle** [comment]
Hello, this is an old post but I've just installed the latest versions of react-redux-toastr and I'm getting the exact same error. I'm using the react boilerplate from https://github.com/react-boilerplate/react-boilerplate

**Comment by KovDimaY** [comment]
I am having it too... :(

**Comment by mseyfayi** [comment]
Document is wrong
rootReducer must be like this:
`const rootReducer = combineReducers({toastr: toastrReducer});
`
