### ISSUE TITLE
IE 11 error - Object doesn't support this action

### ISSUE THREAD

**Issue by valyefimov** [diegoddox/react-redux-toastr#180]
I'm getting the following error when a toastr is dismissed in IE 11, Windows 10. 

![scn-2018-0301-134327-9ttaw](https://user-images.githubusercontent.com/1454782/36843116-8c7e3df0-1d56-11e8-8315-39a4c391c338.png)

To solve the problem and may use a cross-browser event creation like this one:
```
function createNewEvent(eventName) {
    var event;

    if (typeof(Event) === 'function') {
        event = new Event(eventName);
    } else{
        event = document.createEvent('Event');
        event.initEvent(eventName, true, true);
    }

    return event;
}
```

**Comment by diegoddox** [comment]
Hi @vefimov thanks, a PR is more than welcome!

**Comment by tonoslav** [comment]
Why is this still not fixed ?

**Comment by tonoslav** [comment]
What about to use polyfill like this https://github.com/krambuhl/custom-event-polyfill
