### ISSUE TITLE
TypeError: Cannot read property 'preventDuplicates' of undefined

### ISSUE THREAD

**Issue by Thebigbignooby** [diegoddox/react-redux-toastr#185]
```js
const someEpic= action$ =>
  action$.ofType(SOME_ACTION_ERROR)
    .map(() => toastrActions.add({ type: 'error', title: "some message" }));
```

this works fine if I dispatch one action only, but if I trigger this epic multiple times, my app crashes with the error message in the title of this issue.

is this a bug or am I doing something wrong ?

**Comment by Thebigbignooby** [comment]
solved it by removing `preventDuplicates` in the `<ReduxToastr />` component .... but maybe there is something going here ?

**Comment by diegoddox** [comment]
Thanks @Thebigbignooby I will take a look.

**Comment by goldbuick** [comment]
Figured out why this error occurs
when using preventDuplicates

`toastrActions.add({
  type: 'error',
  message: 'blap',
  position: 'bottom-center',
  options: {},
})`

when using preventDuplicates, it requires that you include options:{} in your toastr item

**Comment by Thebigbignooby** [comment]
Ah, well I no longer work on the project where I used this, but good to
know for the future. Might be worth adding something to this effect in the
documentation

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case anyone feels that this has to be addressed.
