### ISSUE TITLE
Update your package.json for redux@4.0.0

### ISSUE THREAD

**Issue by piohan83** [diegoddox/react-redux-toastr#186]
you should update your package.json.
redux 4.0.0 released!! 

when using with redux@4.0.0, 'npm ls' remain this error
![image](https://user-images.githubusercontent.com/807184/39167851-48d5ec06-47cc-11e8-8d14-a8ea69de147a.png)

**Comment by jacoporicare** [comment]
Maybe you can create a pull request and help the author?

**Comment by piohan83** [comment]
@jacoporicare 
In my code, It doesn't have problem yet, so we dont need fix other code.
I just fix package.json that include redux@4.0.0 in peerDependencies. thanks
