### ISSUE TITLE
state.get is not a function

### ISSUE THREAD

**Issue by CameronFraser** [diegoddox/react-redux-toastr#189]
When using redux-persist the react-redux-toastr package throws the following error:
`state.get is not a function`

Minimal example demonstrating error:
https://codesandbox.io/s/3q8zlw9wkm

**Comment by diegoddox** [comment]
Thanks, not sure when I will be able to look at it.

**Comment by brumargues** [comment]
@kamfraser I found that you need to import as `toastr` object instead of `toastrReducer` when adding the reducer.

**It fails on React v16**
`import { reducer as toastrReducer } from 'react-redux-toastr'`

**It works on React v16**
`import { reducer as toastr } from 'react-redux-toastr'`

**Comment by snow-dev** [comment]
It works for me on v16.4.2, just create the reducer:
``
import {reducer as toastrReducer} from 'react-redux-toastr';
export default combineReducers({
    toastr: toastrReducer,
});
``

**Comment by abdulmanan7** [comment]
I am having similar issue ! any help

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case anyone feels that this has to be addressed.
