### ISSUE TITLE
Why did you remove the `src` dir?

### ISSUE THREAD

**Issue by tylercollier** [diegoddox/react-redux-toastr#19]
Your instructions in the README say to do this:

```
2. Add the react-redux-toastr css link to your app
NOTE: This can be change at anytime
<link href="http://diegoddox.github.io/react-redux-toastr/3.0.0/react-redux-toastr.min.css" rel="stylesheet" type="text/css">
```

But I prefer:

```
import 'react-redux-toastr/src/less/react-redux-toastr'
```

Now I can't do that because the `src` directory is missing. If I try to use the `lib/react-redux-toastr.css`, it complains that the `../fonts/redux-toastr.eot` is missing, etc, so it looks like the `fonts` directory was removed too.

**Comment by diegoddox** [comment]
well there is some code that I don't think is necessary to include in `npm` but I will separate and publish with the `src` folder.

**Comment by tylercollier** [comment]
Can you include instructions in the README for how to use the style files without pulling from a CDN? Don't include the entire `src` folder if it's not needed / you don't want to, but we need at least need the dependencies, such as the `.eot` font files.

**Comment by diegoddox** [comment]
@tylercollier I will fix this tomorrow and come back to you with more info.

**Comment by tylercollier** [comment]
Take your time with it. I am using 3.0.4 for now.

**Comment by diegoddox** [comment]
@tylercollier upgrade to 3.0.8 `import 'react-redux-toastr/src/less/index.less'` and you're read to rock!

**Comment by tylercollier** [comment]
I did and it works, thanks!
