### ISSUE TITLE
No buttons in confirm window in IOS.

### ISSUE THREAD

**Issue by bbr0wn** [diegoddox/react-redux-toastr#190]
Don't see any buttons using the toastr confirm method on an IOS device. For example

            const options = {
                okText: "Yes",
                cancelText: "No",
                onOk: () => { console.log("Ok Clicked"); },
                onCancel: () => { console.log("Never mind") },
            }
            toastr.confirm("Do you see any buttons on an IOS device?", options);

displays a window with the text but no buttons.

React 16
react-redux-toastr 7.2.6

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case anyone feels that this has to be addressed.
