### ISSUE TITLE
Configure root ReduxToastr element per severity.

### ISSUE THREAD

**Issue by JoshMcCullough** [diegoddox/react-redux-toastr#191]
Is there an option to supply specific configuration based on severity? E.g., set some default config and then override based on severity...

```
<ReduxToastr timeOut={4000} ...>
    <Error timeOut={0}/>
</ReduxToastr>
```

Above, any toast would timeout in 4 seconds unless it is of _error_ severity, in which case it would not timeout and require user interaction.

**Comment by diegoddox** [comment]
Hi, not at the moment.

**Comment by JoshMcCullough** [comment]
I noticed that setting `timeOut` (note the case) doesn't seem to have any affect. Is this a known issue or am I doing something wrong ...

```
<ReduxToastr timeOut={4000} ... />
```

**Comment by diegoddox** [comment]
You're doing right, I'm not sure if we already have an issue on ti.

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case anyone feels that this has to be addressed.
