### ISSUE TITLE
Feature request: close toastr on clicking

### ISSUE THREAD

**Issue by liuliquan** [diegoddox/react-redux-toastr#194]
Some users have habit to close a toastr by clicking it (not only through the close button, but also the entire toastr div), it will be kind to support this feature.

**Comment by diegoddox** [comment]
Sure, just need to think how this has to work when we do have the close button displaying

**Comment by hugobessa** [comment]
I made a PR and just stopped the bubbling when clicking the close button. Do you think this is ok?
