### ISSUE TITLE
showCloseButton is not true by default

### ISSUE THREAD

**Issue by stevemao** [diegoddox/react-redux-toastr#200]
Not sure if this is a bug or docs not updated yet. I'm using the lastest react-redux-toastr published on npm.

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case you feel that this has to be addressed.

**Comment by stevemao** [comment]
I wasn't sure if which should be fixed: docs or code. Once you give the direction I can submit a PR.

**Comment by diegoddox** [comment]
Hi @stevemao, it will be a good help if you could update the docs.
Thanks in advance.
