### ISSUE TITLE
showCloseButtonOnHover

### ISSUE THREAD

**Issue by aaronbeall** [diegoddox/react-redux-toastr#201]
Is there currently a way to show the close button only on hover? IMO this would would work well with `timeout`, where showing the close button seems a bit unnecessary, but once the user mouses over the toast there isn't a clear way to close it.

**Comment by diegoddox** [comment]
Sorry, I didn't have the opportunity to respond to you but because of inactivity I will close this issue but feel free to reopen in case anyone feels that this has to be addressed.
