### ISSUE TITLE
Option for no icon

### ISSUE THREAD

**Issue by aaronbeall** [diegoddox/react-redux-toastr#202]
Having an icon is nice but in some cases you might not want one at all. In order to do this I had to pass in a CSS class that hid the icon and made the content container full size. It would have been nice if `icon` could simply be set to `null` or `"none"` (including with the `.success()`, `.info()`, etc methods).

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case you feel that this has to be addressed.
