### ISSUE TITLE
title/message, component and preventDuplicates

### ISSUE THREAD

**Issue by aaronbeall** [diegoddox/react-redux-toastr#203]
This is not a definite bug, more an API short-coming, and I don't have a well-defined solution (without breaking APIs) but I ran into this issue:

- I used the `preventDuplicates` option, it was just what I wanted.
- I used the `component` toast option to render some special content. For example just an image.
- I passed `""` for both `title` and `message` because there's no generic text with my special content.
- The `preventDuplicates` seemed to prevent multiple toast from ever appearing.

I eventually figured out its because `preventDuplicates` is using `title` and `message` to determine if toasts are duplicates, but I was using `""` for both those values in all cases and instead rendering unique content with the `component` option. I looked for some kind of `id` or `key` toast option and found none. I found a workaround to pass in a unique `title` (used sort of like a key) and hid the text via a CSS class.

Suggested solution:
- The `title` and `message` could be passed as props to the `component` and not rendered by default in the toast. Or to prevent backwards breaking changes I guess we'd need a separate `render` function or something.
- Add an optional `key` toast method option. If supplied, this is the key that `preventDuplicates` uses. If not supplied it can use the existing behavior of comparing `title` and `message` text.

**Comment by BilyachenkoOY** [comment]
Why `preventDuplicates` doesn't check passed identifier?

**Comment by diegoddox** [comment]
Because of inactivity, I will close it.

**Comment by aaronbeall** [comment]
This is still an issue, though? I'll see if I can put together a PR, it'll also require some doc update
