### ISSUE TITLE
How to Update Content Of Toast  (Feature Request)

### ISSUE THREAD

**Issue by nzhtrtlc** [diegoddox/react-redux-toastr#205]
Hi, is it possible to make something like that;

When i click a button a several request going to API then response back. I am displaying a toast message while this requests are in progress but i also want to update the content of toast message like; 
"1 of 10 record saved"
"2 of 10" records saved"
"3 of 10" records saved"
...

If you don't have a feature like this then can you give me a tip to develop that, i am thinking about the fork project and develop this feature my self.
But i don't know the code base..
Thanks for help.

**Comment by nzhtrtlc** [comment]
I did something
https://drive.google.com/file/d/1vDEQtuJ7CIv3k9g5cESoXWunb8eZhZt_/view

I created a pull request.
https://github.com/diegoddox/react-redux-toastr/pull/206

**Comment by diegoddox** [comment]
Hi @nzhtrtlc thanks I will take a look at it.

**Comment by Xtinct** [comment]
@diegoddox, any updates on this? Very useful feature.

**Comment by diegoddox** [comment]
@Xtinct this is not the first priority and I do believe that this feature goes beyond in what a Toastr should do.

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case anyone feels that this has to be addressed.
