### ISSUE TITLE
Warning: Invalid value for prop `remove` on <div> tag

### ISSUE THREAD

**Issue by tonoslav** [diegoddox/react-redux-toastr#207]
Hello I sometimes get this error message:

> Warning: Invalid value for prop 'remove' on \<div\> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM.
    in div
    in div (created by ToastrBox)
    in div (created by ToastrBox)
    in div (created by ToastrBox)
    in ToastrBox (created by ReduxToastr)
    in span (created by ReduxToastr)
    in div (created by ReduxToastr)
    in span (created by ReduxToastr)
    in span (created by ReduxToastr)
    in ReduxToastr (created by Connect(ReduxToastr))
    in Connect(ReduxToastr) (created by App)

But I can't reproduce it 

"react-redux-toastr": "^7.3.0"
"react": "^16.4.2",

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case anyone feels that this has to be addressed.
