### ISSUE TITLE
Toast removal duration after mouse-out is short, and seemingly not configurable

### ISSUE THREAD

**Issue by jayantbh** [diegoddox/react-redux-toastr#208]
If you hover on a toast, and then mouse-out, the toast disappears in about a second. Can this be disabled or configured? Can the timer be just resumed from where it stopped using some option?

**Comment by diegoddox** [comment]
at the moment no, you can't

**Comment by goxr3plus** [comment]
@diegoddox  Any updates on this ?

**Comment by diegoddox** [comment]
@goxr3plus unfortunately no.
