### ISSUE TITLE
Event listener and event dispatcher related console errors

### ISSUE THREAD

**Issue by jayantbh** [diegoddox/react-redux-toastr#209]
<details>
<summary>Error 1: Uncaught TypeError: Cannot read property 'addEventListener' of null </summary>

```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at onCSSTransitionEnd (utils.js:145)
    at ToastrBox._setTransition (ToastrBox.js:349)
    at ToastrBox._removeToastr (ToastrBox.js:333)
```
  
| onCSSTransitionEnd | @ | utils.js:145
| --- | --- | --- |
| _setTransition | @ | ToastrBox.js:349
| _removeToastr | @ | ToastrBox.js:333
| setTimeout (async) |   |  
| componentDidMount | @ | ToastrBox.js:150

</details>

<details>
<summary>Error 2: Uncaught TypeError: Cannot read property 'dispatchEvent' of null</summary>

```
Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at utils.js:134
```

|(anonymous) | @ | utils.js:134 |
| --- | --- | --- |
| setTimeout (async) |   |  
| onCSSTransitionEnd | @ | utils.js:131 |
| _setTransition | @ | ToastrBox.js:349 |
| _removeToastr | @ | ToastrBox.js:333 |
| setTimeout (async) |     |  
| componentDidMount | @ | ToastrBox.js:150 |

</details>

**Comment by diegoddox** [comment]
@jayantbh there is a new release that should fix this issue.

**Comment by diegoddox** [comment]
feel free to re-open if you still have this issue after upgrading.
