### ISSUE TITLE
Feature request: Slide-in/out (from left or right) animation support.

### ISSUE THREAD

**Issue by jayantbh** [diegoddox/react-redux-toastr#210]
Hi! I'd take a moment to say that this is a really great project, and I hope this gets even better.

It would be really nice if it had slide-in/out animation support.
I believe it's not as _visually loud_ as the bounce animations, and is yet more attention grabbing than the fade in animation.

The MacOS and Windows notifications use Slide-In/Out too, just as examples for popular usage of notifications.

**Comment by diegoddox** [comment]
@jayantbh thanks, will keep in mind.

**Comment by diegoddox** [comment]
Because of inactivity I will close this issue but feel free to reopen in case you feel that this has to be addressed.
