### ISSUE TITLE
this.closeButton.focus() throws an error

### ISSUE THREAD

**Issue by hLittle** [diegoddox/react-redux-toastr#214]
https://github.com/diegoddox/react-redux-toastr/commit/9b75b55b9fc1c2e2993a39a31eeeaae47683b8d9#diff-d22cbee4113c91156a6cde6132dd6908R78

Looks like this change was added recently to move focus to the close button, but it throws an error if the close button was not rendered.

The function renderToastr checks the option "showCloseButton" before rendering the close button, and this render function is what sets the reference for `this.closeButton`

<img width="479" alt="screen shot 2018-12-03 at 6 01 06 pm" src="https://user-images.githubusercontent.com/541910/49407097-7bf05a00-f725-11e8-8512-ac3e9d1fbfa7.png">
<img width="546" alt="screen shot 2018-12-03 at 6 00 52 pm" src="https://user-images.githubusercontent.com/541910/49407103-83affe80-f725-11e8-9620-34fe8e2c42a3.png">
<img width="653" alt="screen shot 2018-12-03 at 6 00 27 pm" src="https://user-images.githubusercontent.com/541910/49407115-8c083980-f725-11e8-85f6-05b211063ff6.png">
<img width="579" alt="screen shot 2018-12-03 at 6 02 44 pm" src="https://user-images.githubusercontent.com/541910/49407153-ab06cb80-f725-11e8-8dea-9840ce52d88b.png">

This is a problem with version 7.4.3

**Comment by diegoddox** [comment]
Thanks @hLittle, @ceall I think this is related to your PR.

**Comment by ceall** [comment]
Hi @hLittle @diegoddox , I hadn't considered a case where no close control would exist. I have just submitted a PR that considers that now

**Comment by OriAmir** [comment]
happened to me also. there is some soultion ? tnx

**Comment by CalvinMills** [comment]
Hi, I know this issue is closed, but I think I'm experiencing a similar issue on 7.4.4 on unmounting of the toastr.

![image](https://user-images.githubusercontent.com/6915748/49806730-5f20db80-fd50-11e8-9d9b-4239c4bcead8.png)

![image](https://user-images.githubusercontent.com/6915748/49806797-8081c780-fd50-11e8-9cc7-451236ae4ea2.png)

Im not raising the toast from a button click or component but rather dispatching a toast on a success in a redux action.

Simple fix would be to check that the element exists before attempting to focus on it, but not sure if the fact that there is no element with the "toastr-control" class is the actual problem as apposed to the lack of an undefined check

Thanks in advance :)

**Comment by ceall** [comment]
@CalvinMills that's not what's in the src folder of 7.4.4

**Comment by CalvinMills** [comment]
My apologies, the line number and syntax as a result of some webpack loader nuances, however the code is there in src: 

![image](https://user-images.githubusercontent.com/6915748/49808000-5ed60f80-fd53-11e8-8f95-1bc1f28cf775.png)

**Comment by CalvinMills** [comment]
@ceall I agree that it isn't in the src folder, it is, however, in the lib folder in the npm package which is the default directory for imports. Any way we can get that change put into the lib folder on the npm package ? Thanks again

**Comment by dardanll** [comment]
It's happening to me as well

<img width="1017" alt="screen shot 2018-12-12 at 1 19 56 am" src="https://user-images.githubusercontent.com/14232700/49838706-41815f80-fdac-11e8-87cd-4d56fd4f38cd.png">

**Comment by ceall** [comment]
@dardanll @CalvinMills 

https://github.com/diegoddox/react-redux-toastr/issues/216

**Comment by CalvinMills** [comment]
@ceall  You da bomb.

**Comment by TsvetomirGeorgiev** [comment]
react-redux-toastr@7.4.5 is released and the cjs build seems to be correct. Cheers ;)

**Comment by barrard** [comment]
Hi, I have the toastr emit successful form submission, and the toast causes the form to lose focus, can we prevent this set focus all together but still keep the close button?
