### ISSUE TITLE
npm package not updated

### ISSUE THREAD

**Issue by keown** [diegoddox/react-redux-toastr#216]
Hi,
I don't know if this is the right place to report this but the compiled version of `ToastrBox` is not compiled with the last source code and it doesn't contain the closeButton fix.

https://github.com/diegoddox/react-redux-toastr/commit/4ea81f7e339f1f084f52de5b082df27a8959fe79

**Comment by diegoddox** [comment]
Thanks @keown, I will take a look!

**Comment by tomasztomys** [comment]
+1

**Comment by thomasMary** [comment]
Hi @diegoddox is there any update on that? Thanks

**Comment by ghost** [comment]
Yeah. We're waiting for this fix too.
PS Merry Christmas.

**Comment by thomasMary** [comment]
@ceall thanks for looking at this issue, we've noticed the "closeButton fix" has been done, and we can see it on master, however, the version in the `lib` folder on NPM still doesn't (version 7.4.4). Must be an issue with the way you publish this package.
(cc @diegoddox)

**Comment by ceall** [comment]
Hi @thomasMary 

I am not an admin on this project

**Comment by TsvetomirGeorgiev** [comment]
react-redux-toastr@7.4.5 is released and the cjs build seems to be correct. Cheers ;)
