### ISSUE TITLE
Option not to escape HTML in message

### ISSUE THREAD

**Issue by Vadorequest** [diegoddox/react-redux-toastr#226]
Is HTML escaped in the message by default?

I'm doing the following

```js
let message = errorsAmount > 1 ? `${errorsAmount} sont survenues.` : `Une erreur est survenue.`;
      message += `<br />Vérifiez d'avoir bien rempli tous les champs du formulaire !`;
      message += `<br />Champs manquants: ${map(fields, v => capitalize(v)).join(', ')}`;
      toastr.error(`Erreur`, message, {
        position: 'bottom-left', // Because in production, in the iframe, we don't see them if they're on top
        escapeHtml: false,
      });
```

which displays this:

![image](https://user-images.githubusercontent.com/3807458/52716608-6efeab00-2f9f-11e9-8b9c-3ffd77180e8d.png)

Am I doing something wrong? I'd assume using HTML within the message would be tolerated, maybe through a flag if not enabled by default for security reasons.

**Comment by jozsefs** [comment]
Have you tried the component prop:

```
toastr.error(`Erreur`, {
  position: 'bottom-left',
  component: <p>Some<br/>Line<br/>Breaks</p>
})
```

**Comment by diegoddox** [comment]
Hi @Vadorequest, there is no`escapeHtml` option on any of the toasts methods and if you wanna use HTML tags you do need to use `dangerouslySetInnerHTML ` in your custom component.

maybe something like this.
```
toastr.error(`Erreur`, {
  position: 'bottom-left',
  component: <p dangerouslySetInnerHTML={{ __html: 'Some<br/>Line<br/>Breaks' }} />
})
```

**Comment by Vadorequest** [comment]
Thank you both, I used the `component` option which is the intended/cleanest way.

```js
toastr.error(title, {
        position: 'bottom-left', // Because in production, in the iframe, we don't see them if they're on top
        timeOut: fields.length * 4000, // Display the message 4s per error, so that the user has time to see all missing fields (UX)
        component: <p dangerouslySetInnerHTML={{ __html: message }} />,
        closeOnToastrClick: false,
      });
```

**Comment by Vadorequest** [comment]
It does generate a react warning though:

> Warning: Invalid value for prop `remove` on `<p>` tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior
    in p (at SimulatorForm.js:80)
    in div (created by ToastrBox)
    in div (created by ToastrBox)
    in div (created by ToastrBox)
    in ToastrBox (created by ReduxToastr)
