### ISSUE TITLE
Warning: Function components cannot be given refs. Attempts to access this ref will fail.

### ISSUE THREAD

**Issue by codejoncode** [diegoddox/react-redux-toastr#233]
I'm getting a warning in my console output since upgrading my application to react v16 and react-redux-toastr to v7.5.1.

This occurs when I use toastr.confirm -- it looks like it is the toastr confirmation buttons that are causing the issue.

Warning: Function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `ToastrConfirm`.
    in ReduxConfirmButton (created by ToastrConfirm)
    in div (created by ToastrConfirm)
    in div (created by ToastrConfirm)
    in div (created by ToastrConfirm)
    in ToastrConfirm (created by ReduxToastr)
    in span (created by ReduxToastr)
    in ReduxToastr (created by Connect(ReduxToastr))
    in Connect(ReduxToastr) (created by App)
    in div (created by App)
    in Provider (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in AppContainer

**Comment by codejoncode** [comment]
Seems to be still on going.

**Comment by diegoddox** [comment]
@codejoncode thanks, will take a look when possible

**Comment by diegoddox** [comment]
because of inactivity, I will close it but feel free to re-open if you're still facing this issue
