### ISSUE TITLE
Not valid HTML

### ISSUE THREAD

**Issue by BilyachenkoOY** [diegoddox/react-redux-toastr#241]
Pasting HTML code into [W3C validator](https://validator.w3.org/#validate_by_input) shows the following error:
![w3c validation results](https://user-images.githubusercontent.com/10833213/60187645-965f6180-9836-11e9-9d2a-d3241856021e.png)

**Comment by diegoddox** [comment]
Thanks @BilyachenkoOY

**Comment by UncleJart** [comment]
Is there any news on this issue?

**Comment by UncleJart** [comment]
I've created [pull request regarding to this issue](https://github.com/diegoddox/react-redux-toastr/pull/245). Could you please look at it when you'll have time?

**Comment by Garik-LN** [comment]
Thanks @BilyachenkoOY and @UncleJart

**Comment by diegoddox** [comment]
Thanks @UncleJart

**Comment by diegoddox** [comment]
This should be fixed on the latest version
