### ISSUE TITLE
CSS loaded by import not working

### ISSUE THREAD

**Issue by fbaprojetos** [diegoddox/react-redux-toastr#243]
I import css by `import 'react-redux-toastr/lib/css/react-redux-toastr.min.css'` but this is not working and simply the toastr is without styles. Inserting `<link href="https://diegoddox.github.io/react-redux-toastr/7.1/react-redux-toastr.min.css" rel="stylesheet" type="text/css">` in index.html file work fine.
I'm using the project created by the `create-react-app` tool and I believe the webpack has css-loader but I can not guarantee it.

**Comment by diegoddox** [comment]
I'm not sure either but try to investigate/ask with them first.
