### ISSUE TITLE
7.6.0 entirely breaks Enzyme mount() tests

### ISSUE THREAD

**Issue by favna** [diegoddox/react-redux-toastr#248]
After upgrading from 7.5.2 to 7.6.0 I noticed that our Enzyme powered `mount()` tests completely fail. We use Enzyme's Full DOM rendering for Connected components as these cannot be properly tested with Enzyme's Shallow rendering. I have determined that 7.6.0 is the reason by specifying my version to `~7.5.2` and the error does not occur. This is the full log of running the tests, including both stdout and stderr: https://hasteb.in/otewahat.txt

**Comment by paulincai** [comment]
Using Meteor here. I don't seem to have a problem in development, but in production I get a console error and the webapp fails. Getting back to the previous version now.


![Screen Shot 2019-10-05 at 04 31 27](https://user-images.githubusercontent.com/26188915/66246895-0e3c0280-e729-11e9-94d8-f7c314d04909.png)

**Comment by diegoddox** [comment]
Thanks guys, I've already made another release
