### ISSUE TITLE
Demo site non-functional

### ISSUE THREAD

**Issue by rmckeel** [diegoddox/react-redux-toastr#253]
The demo site at https://diegoddox.github.io/react-redux-toastr/ is non-functional (no visible HTML or text other than some basic colored divs).  This is on Chrome and FireFox latest, and also does the same with the local demo after `npm install`.

May be due to this console error that is tripping up the load:
`file.myfontastic.com/DK4y3Mj8zxvX2ADWpcWGnM/icons.css:1 Failed to load resource: net::ERR_CERT_DATE_INVALID`

**Comment by diegoddox** [comment]
Thanks @rmckeel

**Comment by mergebandit** [comment]
FWIW - was going to implement this for a large enterprise client but this issue (and the fact that it's months old) has led me to choose a different solution.

**Comment by diegoddox** [comment]
For those who still experience this issue, `react-redux-toastr` has reach the limit on the amount of request to fontastic.com fonts CDN. That's why you're not able to see the icon.

@mergebandit this is an open-source project like others feel free to use it or not, or even better in case of an issue create a PR and help those who have invested time on something they haven't got any payment for it.

**Comment by mergebandit** [comment]
It's more than just not being able to see an icon - the demo page provides no indication that it's functional.

![image](https://user-images.githubusercontent.com/22401430/74159465-d61e6200-4be9-11ea-94db-7a96122f1fb4.png)

Not dogging you at all. I appreciate open source work immensely - just highlighting that a broken demo page is likely to cause a lot of churn for potential adoption.

**Comment by diegoddox** [comment]
@mergebandit I know that you're not dogging me.
Thanks for your feedback.

**Comment by diegoddox** [comment]
<img width="1680" alt="Screenshot 2020-02-10 at 15 45 00" src="https://user-images.githubusercontent.com/2768497/74159623-5c539c00-4c1c-11ea-9f36-b1ed5e9c0e8b.png">

@mergebandit As u can see I'm able to click on the button even though there is no icon.

**Comment by diegoddox** [comment]
this is because I'm using a free version of embeddable icons and I have a limit of requests on the site.
