### ISSUE TITLE
GetState missing from ReduxToasterProps in TS

### ISSUE THREAD

**Issue by MoJama1995** [diegoddox/react-redux-toastr#255]
Hi. 

While following your tutorial on how to use React-Redux-Toaster, we noticed that adding in the TSX attribute getState was missing from your ReduxToastr props in the type definitions .

On line 131 in your typeDefinitions - 
` export default class ReduxToastr extends Component<ReduxToastrProps> {}` 

and your ReduxToastrProps 

```
interface ReduxToastrProps {
    confirmOptions?: {
        cancelText: string;
        okText: string;
    };
    newestOnTop?: boolean;
    options?: any; // This is currently not used, waiting for response from the package author to remove
    position?: positionType;
    preventDuplicates?: boolean;
    progressBar?: boolean;
    timeOut?: number;
    toastr?: ToastrState;
    transitionIn?: transitionInType;
    transitionOut?: transitionOutType;
    className?: string;
    closeOnToastrClick?: boolean;
}
```
When getting to step 4 of your tutorial, we're getting an error based on the fact that `get state`  isn't on the component props - any potential fixes for this? 

Thanks

**Comment by diegoddox** [comment]
Hi @MoJama1995 at the moment I'm not using typescript so this will not be possible.
https://www.npmjs.com/package/@types/react-redux-toastr
