### ISSUE TITLE
Method to remove all toasts?

### ISSUE THREAD

**Issue by Nantris** [diegoddox/react-redux-toastr#256]
I know there's a method to remove toasts by `type` and by `id`, but is there a quick and easy way to clear _all_ toasts?

**Comment by diegoddox** [comment]
Hi @Slapbox,
Unfortinually at the moment, it is not possible.

**Comment by Nantris** [comment]
@diegoddox thanks for the update. I think this would be a great feature to consider, but I know that actual implementation requires actual work.

**Comment by diegoddox** [comment]
@Slapbox sorry, there is a method to remove all toastrs [clean](https://github.com/diegoddox/react-redux-toastr/blob/master/src/actions.js#L29)

**Comment by Nantris** [comment]
Ha hey that's nifty! Thanks for the update @diegoddox!
