### ISSUE TITLE
Is it possible to customise this component so that it follows material guidelines?

### ISSUE THREAD

**Issue by shiraze** [diegoddox/react-redux-toastr#258]
Is it possible to customise the appearance of the toaster messages so that they follow these guidelines?
https://material.io/components/snackbars/

Mainly, allow removal of the left/right icons, and allow a single line of text only.

**Comment by diegoddox** [comment]
At the moment unfortunately we can't.

**Comment by MarshalX** [comment]
Hi in 2022. Any news?)

**Comment by diegoddox** [comment]
Hi @MarshalX No,
