### ISSUE TITLE
Include the 'fonts' directory in lib

### ISSUE THREAD

**Issue by kbrownlees** [diegoddox/react-redux-toastr#26]
Currently the css files that end up in the lib folder have:

```
src: url("../fonts/redux-toastr.eot");
```

but the fonts directory does not exist so it fails to import.

**Comment by diegoddox** [comment]
what is the version you're using?

**Comment by kbrownlees** [comment]
3.1.2

**Comment by diegoddox** [comment]
are you including via `import`?

**Comment by diegoddox** [comment]
anyway I do have update the css files just remove the cache and reload your app

**Comment by kbrownlees** [comment]
```
$> npm install react-redux-toastr
├── UNMET DEPENDENCY react@^15.0.2
├── UNMET DEPENDENCY react-redux@^4.4.5
├─┬ react-redux-toastr@3.1.2 
│ ├── classnames@2.2.5 
│ ├── eventemitter3@1.2.0 
│ ├─┬ fbjs@0.8.1 
│ │ ├─┬ babel-plugin-syntax-flow@6.8.0 
│ │ │ └─┬ babel-runtime@6.6.1 
│ │ │   └── core-js@2.3.0 
│ │ ├── core-js@1.2.6 
│ │ ├─┬ isomorphic-fetch@2.2.1 
│ │ │ ├─┬ node-fetch@1.5.1 
│ │ │ │ ├─┬ encoding@0.1.12 
│ │ │ │ │ └── iconv-lite@0.4.13 
│ │ │ │ └── is-stream@1.1.0 
│ │ │ └── whatwg-fetch@1.0.0 
│ │ ├─┬ loose-envify@1.1.0 
│ │ │ └── js-tokens@1.0.3 
│ │ ├─┬ promise@7.1.1 
│ │ │ └── asap@2.0.3 
│ │ └── ua-parser-js@0.7.10 
│ └── uuid@2.0.2 
└── UNMET DEPENDENCY redux@^3.5.2

npm WARN react-redux-toastr@3.1.2 requires a peer of react@^0.14 || ^15.0.1 but none was installed.
npm WARN react-redux-toastr@3.1.2 requires a peer of react-redux@^4.0.1 but none was installed.
npm WARN react-redux-toastr@3.1.2 requires a peer of redux@^3.0.5 but none was installed.
$> ls node_modules/react-redux-toastr/lib
actions.js  Button.js  config.js  constants.js  css  index.js  reducer.js  ReduxToastr.js  ToastrBox.js  ToastrConfirm.js  toastrEmitter.js  utils.js
```

The fonts folder only exists the _src_ directory, not the _lib_ directory.

**Comment by diegoddox** [comment]
Yes but if you're including the `react-redux-toastr/src/index.less` the src file is pointing to the github-page

**Comment by kbrownlees** [comment]
I want to include the css file, but they point at ../fonts which doesn't exist (in lib)..

**Comment by diegoddox** [comment]
OK I see the problem, you are including the style from the `lib` folder and not from the `src`.
This is because the `lib` folder contains an old version but I will publish a new with this fixed.

**Comment by diegoddox** [comment]
can you please update to `3.1.3` and tell me if is working?

**Comment by kbrownlees** [comment]
I am not sure hard coding the fonts to be fetched over http from github is really an improvement? The previous system worked perfectly for my use case (stand alone bundle) except the fonts folder didn't make it into lib. I will just stick with 3.1.2 and my hack to move the fonts folder :)

**Comment by diegoddox** [comment]
Could you give some reasons for why not loading fonts via http?

**Comment by kbrownlees** [comment]
If you try and load http content from an https site the browser will show an error page.

**Comment by diegoddox** [comment]
The fonts are on the `lib` folder on the lasted version.
