### ISSUE TITLE
onMouseEnter clears timeout in ToasterBox.js

### ISSUE THREAD

**Issue by adamlucz90** [diegoddox/react-redux-toastr#262]
In the `ToasterBox.js` file on line `144` the below `onMouseEnter` function clears the timeout which causes the toast to persist indefinitely.  

```
mouseEnter = () => {
    clearTimeout(this.intervalId);

    this._setIntervalId(null);
    this._setIsHiding(false);

    const {progressBar} = this.props.item.options;
    const timeOut = this._getItemTimeOut();

    if (timeOut && progressBar) {
      this.setState({progressBar: null});
    }
  };
```

This is an issue if you have `removeOnHover: false` and `showCloseButton: false` because now there is no way to remove the toast.  Can we check to make sure there is a way to remove the toast before we `clearTimeOut`?

**Comment by diegoddox** [comment]
Hi, closing it but feel free to re-open in case u need this still an issue.
