### ISSUE TITLE
Why doesn't this library works with linux ?

### ISSUE THREAD

**Issue by pranjalsuyal** [diegoddox/react-redux-toastr#264]
I have my code perfectly running on my macbook but I was trying to run the same code on my ubuntu machine it is throwing the following error:
Please note that I have tried using multiple ubuntu devices all having the same result but works perfectly fine when using mac.
![Screenshot from 2020-08-06 14-54-23](https://user-images.githubusercontent.com/51028500/89515514-d5f7cb80-d7f4-11ea-8fdb-d74ec04c1625.png)

**Comment by pranjalsuyal** [comment]
![reactToaster_npmInstall](https://user-images.githubusercontent.com/51028500/89515724-23743880-d7f5-11ea-9525-822812fafcfe.png)
Also while trying to run demo I get following error after running npm install

**Comment by diegoddox** [comment]
Hi @pranjalsuyal, the webpack setup is quite old not to mention that the packages has not been updated in a while.
Not sure when I will have the time to take a look at it.

**Comment by pranjalsuyal** [comment]
ok sure, thank you!
