### ISSUE TITLE
No intuitive way to resize a confirmation dialog

### ISSUE THREAD

**Issue by hope-portal-services** [diegoddox/react-redux-toastr#267]
The ability to add an `id` to the `toastrConfig` partially solves this. If you use this ID to target the `.rrt-confirm` class and change the default `320px` to something higher, but it then skews the negative margin on the `.rrt-confirm` element. Setting the negative margin to half of the desired width of the confirmation element solves the problem visually until the browser scales down, in which case now you've started a whole project to customize an out of the box component.

Would be great to have a `width` property on the `toastrConfig` object that handled the necessary adjustments to resize the dialog.

**Comment by diegoddox** [comment]
I'm rewriting the lib and will take note about it. For now the best is to override the styles as you've mentioned above.

**Comment by diegoddox** [comment]
Hi, closing it but feel free to re-open in case u need this feature.
