### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by nick4fake** [diegoddox/react-redux-toastr#269]
Looks like code should be updated.

````
Recommendation: math.div($with, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
49 │       margin-left: -($with / 2);
   │                      ^^^^^^^^^

````

**Comment by diegoddox** [comment]
Hi @nick4fake Thanks, I will close but will for sure have a look when the time to upgrade our dep comes.

**Comment by nick4fake** [comment]
Hi @diegoddox 

https://github.com/diegoddox/react-redux-toastr/blob/master/src/styles/index.scss#L39

It is not a dependency issue, the code is part of redux-toastr

**Comment by diegoddox** [comment]
@nick4fake thanks, if you have time feel free to create a PR <3

**Comment by uxtx** [comment]
@diegoddox I've created a PR for this - thanks again for the lib!

**Comment by diegoddox** [comment]
Thanks @uxtx ! I will have a look during this week
