### ISSUE TITLE
Toaster 7.6.0 Text input is blurred when the toast shows up

### ISSUE THREAD

**Issue by goxr3plus** [diegoddox/react-redux-toastr#270]
I have seen the issue https://github.com/diegoddox/react-redux-toastr/issues/238

And the given solution doesn't work for me i call the toaster like :

toastr.success(title, message, { disableCloseButtonFocus: true  } )

When the toaster appears it causes the Text Input to blur

@diegoddox @MirayaReie

**Comment by zarv1k** [comment]
@goxr3plus please check at the latest tag - https://github.com/diegoddox/react-redux-toastr/releases/tag/v7.6.5

**Comment by goxr3plus** [comment]
@zarv1k 

Just tested again with the latest https://github.com/diegoddox/react-redux-toastr/releases/tag/v7.6.5 
and Chrome 92 

`toastr.success(title, message, { disableCloseButtonFocus: true } )`

issue is still the same when toaster appears it stills the focus from Text Input and makes it blur

**Comment by goxr3plus** [comment]
Am i using wrong options ? The property ```disableCloseButtonFocus``` doesn't work anymore ?

**Comment by zarv1k** [comment]
@goxr3plus 
> Am i using wrong options ? The property `disableCloseButtonFocus` doesn't work anymore ?

I don't know. Let's check [this example](https://codesandbox.io/s/sweet-tree-fissd). It works!

**Comment by goxr3plus** [comment]
@zarv1k 

What the as any means i have never seen that before :) Even Webstorm doesn't recognize it loccally. It's typescript ?

![image](https://user-images.githubusercontent.com/20374208/130578272-45468e46-e78c-4e2a-a437-d4ede3b1e8da.png)

**Comment by diegoddox** [comment]
Hi @goxr3plus, I wil try to have a look on it and yes that is typescript.
Thanks a lot @zarv1k for your responses and for providing an example.

**Comment by zarv1k** [comment]
@diegoddox the issue should be closed. The option `disableCloseButtonFocus` works well as you can see on my example.

**Comment by traverse** [comment]
I just stumbled upon this problem as well, is there any way to globally disable this behavior? It doesn't seem that you can add it as a prop to the `ReduxToastr` component.
