### ISSUE TITLE
Disable dissapear after hover + setTimeout infinity

### ISSUE THREAD

**Issue by goxr3plus** [diegoddox/react-redux-toastr#273]
What i want to achieve is the user to be able to close the toaster only with the small X.

What should i put on the timeout to make it infinite ?
When the user hovers in and out of the toastr it dissapears how to prevent that ?

I am using the latest version of react-redux-toastr

@diegoddox  Thank you :)

**Comment by diegoddox** [comment]
Hi @goxr3plus [here](https://github.com/diegoddox/react-redux-toastr#toastr-methods) you can see what options you can have
