### ISSUE TITLE
[WEIRD] when enable redux-devtools

### ISSUE THREAD

**Issue by coolblabla** [diegoddox/react-redux-toastr#28]
Hi, awesome work.

First ,I triggered `toastr.error('## Info', "asdasd")` at router /a and wait for message dismiss, then I switched to router /b, the message appeared again! just like `clean action` revoked. I rechecked my code multiple times, every integration step goes fine. Looked into toastr sourcecode, nothing help. At las t, I opened Edge, it runs fine! So finally, I got here :mask: 

It's really weird, I don't know whether or not posting issue to redux-devtools or here.

**Comment by diegoddox** [comment]
Hi @coolblabla  thanks,

1: which browser you're getting this issue?
2: what version are you using?
3: where have you place the `<ReduxToastr />` component?

**Comment by coolblabla** [comment]
Thanks for the rapid reply!
Im using chrome  51.0.2704.84 m (64-bit)    everything goes fine when disable redux-devtools.

```
  render () {
    const { history, routes, routerKey, store } = this.props
    return (
      <Provider store={store}>
        <div style={{ height: '100%' }}>
          <Router history={history} children={routes} key={routerKey} />
          <ReduxToastr />
        </div>
      </Provider>
    )
  }
}
```

**Comment by coolblabla** [comment]
oh, another issue after I `npm installed react-redux-toastr`

"webpack": "^1.12.14",

```
WARNING in ./~/.npminstall/style-loader/0.13.1/style-loader/addStyles.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in d:/dev/frontend/~/.npminstall/style-loader/0.13.1/style-loader/addStyles.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./~/.npminstall/css-loader/0.23.1/css-loader/lib/css-base.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in d:/dev/frontend/~/.npminstall/css-loader/0.23.1/css-loader/lib/css-base.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./~/.npminstall/fbjs/0.8.3/fbjs/lib/invariant.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in d:/dev/frontend/~/.npminstall/fbjs/0.8.3/fbjs/lib/invariant.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```

**Comment by diegoddox** [comment]
Looks fine, are you using the lasted version of the dev-tools?
the warning could be that in your code you are requiring a module/component with camel-case and another place the same module/component with a small-case.

ex:

```
// In one file
import mymodule from 'mymodule'; 

// I another file
import mymodule from 'Mymodule'; 
```

**Comment by diegoddox** [comment]
try remove the node_modules and reinstall everything again!

**Comment by coolblabla** [comment]
@diegoddox 
Thanks.  `Redux DevTools 2.0.0.4`
I've faced this module warning issue before when installed `lodash`, an other module referred a lower version of lodash subset, I think it maybe deferent version refering issue during webpack compiling.

**Comment by diegoddox** [comment]
no problem, have u try delete the node_modules folder and reinstall?

**Comment by coolblabla** [comment]
yes, I've done that multiple times :mask:  warning gone after `uninstall lodash`

**Comment by diegoddox** [comment]
what about the `dev-tools/toastr` issue?

**Comment by coolblabla** [comment]
Still no solution except disable redux-devtools. Any comments?

**Comment by diegoddox** [comment]
@coolblabla no, try open an issue on the dev-tools repo and see what they say.

**Comment by diegoddox** [comment]
@coolblabla any news on this issue?

**Comment by diegoddox** [comment]
I will close but feel free to open in case you need.

**Comment by zalmoxisus** [comment]
Related to https://github.com/gaearon/redux-devtools/issues/304. `store.replaceReducer` causes Redux Detools to replay actions which is as expected, due to the fact that it is intended to be used for hot-reloading.
