### ISSUE TITLE
Align toastr to center

### ISSUE THREAD

**Issue by rachitbhasin** [diegoddox/react-redux-toastr#29]
Hi,

I have been trying to center align the toastr but have not succeeded in doing so.
I went through the documentation and found that the toastr can only be aligned to the four corners of the page.

Is there a way to center align the toastr?

Thanks for the awesome react-redux-toastr

**Comment by diegoddox** [comment]
@rachitbhasin no, this is not possible at the moment! but I will take note and implement later on.

**Comment by rachitbhasin** [comment]
Thanks for taking cognizance of this. Looking forward to this feature. In the meantime I will go through the source code implement this and share with you.

**Comment by diegoddox** [comment]
@rachitbhasin that will be nice! just make a pull-request if you wish.
