### ISSUE TITLE
readme needs updated.  internal styles have a dependency on bootstrap css.

### ISSUE THREAD

**Issue by jonnolen** [diegoddox/react-redux-toastr#3]
Without bootstrap css confirm box displays on load, animates out on ok, and then immediately re-displays, just need to add update to readme to reflect that dependency (or define hide as a style in 1.0.2 css.)

**Comment by diegoddox** [comment]
Thank you very much, can you please tell me which browser you are using.

**Comment by jonnolen** [comment]
Chrome

**Comment by diegoddox** [comment]
Thanks I will take a look as soon as possible.

**Comment by diegoddox** [comment]
Done, now you don't need to include bootstrap.
