### ISSUE TITLE
Invoke component option directly, rather than as a class reference

### ISSUE THREAD

**Issue by whawker** [diegoddox/react-redux-toastr#30]
I'm having issues with the `component` option, as it does not allow me to pass dynamic props. This is due to the expectation of a class reference being passed (i.e. `component: React.Component`), rather than a JSX expression.

In [ToastrBox.js](https://github.com/diegoddox/react-redux-toastr/blob/master/src/ToastrBox.js#L125) we have

``` jsx
{this.props.item.options.component &&
  <div className="message">
    <this.props.item.options.component />
  </div>
}
```

Meaning the options component is rendered with no properties.

What I'd like to be able to do, is to have a dynamically generated component, so I am able to able to pass props (and children) to it. 

i.e.

``` js
toastr.error('An error occurred', `The error code was ${errorCode}` {
  timeout: false
  component: (
    <Link to={`/faqs/error/${errorCode}`}>More information on this error</Link>
  )
});
```

It seems this would only require a simple change to the code

``` jsx
{this.props.item.options.component &&
  <div className="message">
    {this.props.item.options.component} // Curly braces, rather than < angle brackets />
  </div>
}
```

This appears to be much more powerful than the existing solution. Any thoughts?

**Comment by diegoddox** [comment]
That looks good, feel free to implement this improvement!
