### ISSUE TITLE
Compiled CSS file missing in v3.2.0 

### ISSUE THREAD

**Issue by whawker** [diegoddox/react-redux-toastr#33]
Hi,

In the latest version, 3.2.0, the compiled CSS file `lib/css/react-redux-toastr.min.css` is missing? Was this intentional?

Cheers

**Comment by diegoddox** [comment]
It was an accident! please update to the new version.

**Comment by whawker** [comment]
@diegoddox sorry I should have been clearer, the `lib/fonts/` directory is also missing (and is missing in v3.3.0 too)

**Comment by diegoddox** [comment]
@whawker Thanks, my bad :D I've fix (hope)

**Comment by whawker** [comment]
@diegoddox Looks good to me! Thanks!
