### ISSUE TITLE
Programmaticly close a specific toastr

### ISSUE THREAD

**Issue by JamesPortelli** [diegoddox/react-redux-toastr#34]
Hi Deigo,

It would be really awesome if you could provide some way for us to programmitcally close a specific toastr.

Currently I'm using the toastr to display a progress bar for an action I'm performing in my application, which I achieved by passing in a custom component in the toastr options. I want to be able to hide this toastr once the progress has reached 100% and then display a success toastr to the user.

![option 2](https://cloud.githubusercontent.com/assets/17567969/16489544/fb3fc4ac-3ecd-11e6-8111-20896cf96400.PNG)

Do you think you would be able to provide such a feature?

Thanks
James

**Comment by diegoddox** [comment]
Hi @JamesPortelli,
I will add as a feature!

**Comment by diegoddox** [comment]
Now you can call the `this.props.remove()` from your component
