### ISSUE TITLE
More control over the Toasts Options

### ISSUE THREAD

**Issue by JamesPortelli** [diegoddox/react-redux-toastr#35]
Hi Diego,

Would it be possible for you to provide a finer control on how the closing of toastrs works with user interaction.

Be able to:

1) Toggle on/off the hiding of the toastr when you click it
2) Toggle on/off  the hiding of the toastr when you hover in and out of it
3) Provide an option to show a 'x' to close the toastr. (Ive seen this in you demo but cant get it to work for my application)
4) Provide the ability to hide/show the icons
5) Provide the ability to apply custom classes to the toastr.

Thanks
James

**Comment by diegoddox** [comment]
Hi @JamesPortelli,

1 and 2) when you `click` or `hover` the `toastr`, it should close.
so why you wanna a `toggle`?

3) true there is an `x` in the demo site but I've remove, I feel that was unnecessary.
4) not sure but possible!
5) That is possible!

**Comment by JamesPortelli** [comment]
Hi Diego,

1 and 2) I was thinking of the ability to toggle off such behaviour and instead handle the closing of the toastr using the 'x' button which I mentioned in 3.

Looking forward to seeing such features in an already great library. Do you know when these would be available? 

Thanks
James

**Comment by diegoddox** [comment]
@JamesPortelli 
I don't think I will implement (1, 2) as this will break the current behavior but I will add the `className` option to the `toastr` main div.

**Comment by JamesPortelli** [comment]
Hi @diegoddox 

Thanks for getting back to me, wanted to explain my idea in more detail just incase we didnt understand each other since being able to choose how the hiding of toastrs works in my app is quite important.

I was thinking along these lines:

By default the toastrs would work as they currently do, having them hidden after a specified time if you specify a timeOut which is greater than 0, or user invoked by hover, or by click.

If for a specific toastr you specify in the options something like the following:
{
   timeOut: 0,
   hideOnHover: false,
   hideOnClick: false,
   closeButton: true
}
- hideOnHover, hideOnClick: Can maybe be aggegated to something like hideOnUserInteration
- hideOnHover, hideOnClick: By default are true.
- closeButton: By default is false.
- closeButton: Possibly not surfaced as an option and only shown if both hideOnHover, hideOnClick are false

That specific toastr you passed the options to would close on by clicking the 'x'.

This is quite important to my scenario which is that of displaying the progress bar to an action being performed in a toastr. This toastr would remain there untill the progress reaches 100% or the user uses the 'x' button to hide it. 

Do you think this is something you still wouldnt consider implementing?

Thanks 
James

**Comment by JamesPortelli** [comment]
Hi @diegoddox,

Just to let you know while using your library I noticed you left a console.log in the constructor of the ToastrBox component. 

Also i was wondering whether you had a chance to look into my comment above? :)

Thanks
James

**Comment by diegoddox** [comment]
@JamesPortelli Thanks, I do have looked your comments, I'm just trying to avoid coding on saturday and sunday :D 

I'm a bit occupied but I will look into to this request.

**Comment by JamesPortelli** [comment]
@diegoddox, Good rule to stand by! :+1: 

Thanks for looking my request! :smile:

**Comment by JamesPortelli** [comment]
Hey @diegoddox  any updates on the above? :)

**Comment by camperov** [comment]
Would also be cool to be able to change confirm show/hide animation.

**Comment by diegoddox** [comment]
Hi @JamesPortelli 
I'm om vacation but I will implement ASAP and @camperov I will add this options as well.

**Comment by JamesPortelli** [comment]
Hi @diegoddox, hope you had a good vacation. I was just wondering whether you had some time to look into the feature we discussed above?

Thanks
James

**Comment by diegoddox** [comment]
Hi @JamesPortelli,
Sorry but I still on vacation, I will be back next monday.

**Comment by diegoddox** [comment]
I've add `removeOnHover` and `removeOnClick`

**Comment by diegoddox** [comment]
Hi @JamesPortelli  I'm not sure when the button will be available as I'm working in the styles, but you should have a `remove` `props` in your `toastr` component.

**Comment by JamesPortelli** [comment]
Wow @diegoddox extremely efficient thank you will have a look tomorrow! 😁

**Comment by JamesPortelli** [comment]
@diegoddox works perfectly thank you! Now for 'X' button when you can so i can switch them both off and close using it :)

**Comment by diegoddox** [comment]
Hi @JamesPortelli,

Not sure but until there you can create a `component` `button` that has a onClick with the `remove` props that comes with the `toastr` component.

**Comment by JamesPortelli** [comment]
@diegoddox Yeh for now i just left the on click toastr remove on. I thought of doing the above but i dont think it would look nice aesthetically. So ill wait untill you can provide me with the 'x' :)

**Comment by diegoddox** [comment]
@JamesPortelli depend on how you style the button but ok, do what is best for u.

**Comment by JamesPortelli** [comment]
@diegoddox, discovered a couple of bugs. 

1) With the message toastr (Havent tested with others) that has a timeout on it from the toastrOptions, I noticed that the timeOut works as expected as long as you dont hover over the toastr while it is displayed, however if you hover over the toastr before the timeout elapses and then hover back off it, I would expect that it either resumes counting down or restarts the counter and hides when the timeOut elapses, which doesnt happen as it remains until you click it to hide it. 

2) There seems to be a styling issue with the heading of the toastrs in which they are not centered, I presume because the margin for the 'x' button you removed is still there.
![issue](https://cloud.githubusercontent.com/assets/17567969/17621215/ad1ac8e8-6089-11e6-9706-e77bbe290ef2.jpg)

**Comment by diegoddox** [comment]
@JamesPortelli thanks but in the next version there will be no more `message` method and this is because you can inject your own `component`.

**Comment by JamesPortelli** [comment]
@diegoddox that's fine its home I'm using it anyways. Will the scroll bar if the component exceeds a certain height still appear automatically or will this need to be handled by the injected component? 

Also I'm using the message in particular because of the white coloured toastr will there be an alternative way of firing a white toastr?

James

**Comment by diegoddox** [comment]
@JamesPortelli Yes I will provide the method `toastr.custom` that will render a empty `component` with a white bg.

**Comment by grigored** [comment]
+1 for close button option

**Comment by JamesPortelli** [comment]
Hi @diegoddox, hope you are well. Just wanted to check on the progress of the 'x'?

**Comment by diegoddox** [comment]
Hi @JamesPortelli I'm fine thanks, implemented!!

**Comment by diegoddox** [comment]
+2
