### ISSUE TITLE
Confirm box broken - Won't dismiss

### ISSUE THREAD

**Issue by ro-savage** [diegoddox/react-redux-toastr#37]
The confirm box is no longer working. Confirmed on [demo page](http://diegoddox.github.io/react-redux-toastr/) and installing repo locally.

Not sure exactly what going on.

It appears that the utils function `onCSSTransitionEnd` which fires `ReactTransitionEvents.addEndEventListener(node, runOnce);` is being attached but never fired.

It seems to be broken in older versions (3.1.4) as well, so it might be a dependancy breaking? 
Possibly `import CSSCore from 'fbjs/lib/CSSCore';` or `import ReactTransitionEvents from 'react/lib/ReactTransitionEvents';`

**Comment by ro-savage** [comment]
Well that was a long exercise of frustration. 

Bug appears to be in chrome 54.0.2787.0 canary (64-bit). 
`Transition` isn't working for `transform: scale()` on the `::before` pseudo element.

Up to you if you want to leave issue open until Chrome fixed or just close it right away.

**Comment by diegoddox** [comment]
Hi @ro-savage 
Thanks I will leave open!
