### ISSUE TITLE
How to create toaster notification with X icon to close

### ISSUE THREAD

**Issue by TheTFo** [diegoddox/react-redux-toastr#40]
Hello,

Could you provide guidance on how you created the toaster with the X to close, like on the example page?  Is this available out of the box?

Thanks!

**Comment by diegoddox** [comment]
@TheTFo Sorry but the demo page is not updated, in order to close a `toastr` you need to click on the entire component so for that reason I've decide to remove the X button.

**Comment by diegoddox** [comment]
Hi @TheTFo, 
I will close this issue but you can see the progress in #35
