### ISSUE TITLE
timeOut overriden by ReduxToastr props

### ISSUE THREAD

**Issue by Glogo** [diegoddox/react-redux-toastr#41]
I'm trying to use your library to show toasts in our application but I'm having issue with the `timeOut` option

I dispatched this action:

``` javascript
toastrActions.error(
  'Something failed',
  'Should be visible until dismissed',
  { timeOut: 0 }
);
```

But the timeOut gets always overriden by my `ReduxToastr` component prop:

``` javascript
<ReduxToastr
    timeOut={4000}
    newestOnTop={false}
    position="top-right" />
```

I'm getting same results when I try removing the timeOut prop:

``` javascript
<ReduxToastr
    newestOnTop={false}
    position="top-right" />
```

Is there any way to make some Toasts dissappear after timeOut and some (f.e. errors) to keep here until dismissed?

Thank you,
Michael

**Comment by diegoddox** [comment]
Hi @Glogo,

The `timeOut` props is that for, to prevent the `toastr` to close, I will take a look at this issue later on.

Thanks!

**Comment by Glogo** [comment]
Update: after some testing I realized that toasts (either with timeOut={0} prop in `ReduxToastr` or in `toastrActions.success(...)`) as 3d option param get dismissed only after mouseleave event.

We would like to keep toastr message always visible even after hover (f.e. for major error messages that should be dismissed either programatically or by click)

Does it make sense to keep all toasts visible even after mouseleave when timeOut is set to 0 or would be better idea to introduce some new prop (f.e. `noAutoDismiss`) that overrides this behaviour?

**Comment by diegoddox** [comment]
@Glogo It makes sense, there is already a similar request #35

**Comment by diegoddox** [comment]
I will close this issue but u can take a look at #35 for more info!
