### ISSUE TITLE
New NPM release

### ISSUE THREAD

**Issue by meikoudras** [diegoddox/react-redux-toastr#42]
Could we get a new npm release? So the few fixes that have been added (lingering console.log) could be removed from the npm version.

**Comment by diegoddox** [comment]
HI @meikoudras sorry for that, I know is not funny to have a log every time u fire a `toastr` but I still on vacation and without a computer so there is not much I can do now.

I will be back monday next week!! sorry!

**Comment by meikoudras** [comment]
Haha, it is ok! Enjoy your vacation!

**Comment by diegoddox** [comment]
I've add another guy to the npmjs so maybe he will be able to make a new release this week.

**Comment by diegoddox** [comment]
done!

**Comment by camperov** [comment]
Sorry for not releasign new version, had been busy at work lately
And I also do not have full access to github from my corporate network because of strange filrewall settings

**Comment by meikoudras** [comment]
No worries! Thanks for the release !

**Comment by diegoddox** [comment]
@camperov np!
