### ISSUE TITLE
Toastr does not timeout / is not removed.

### ISSUE THREAD

**Issue by Leo-Mahon** [diegoddox/react-redux-toastr#44]
I am getting a behaviour where the toastr sometimes will not close or timeout. I have set the timeout to 3000 and the toastr type is success.

It seems to be intermittent. The Add action fires and then the Remove action does not.

Im using Chrome version  52.0.2743.116 m
react-redux-toastr version 3.1.4
react-redux version 4.0.6
react version 15.1.0
redux version 3.0.5

**Comment by diegoddox** [comment]
This may be a Chrome issue, I will take a look ASAP!

**Comment by Leo-Mahon** [comment]
Thanks!

Also it's worth noting that it will close when you click on it.

**Comment by diegoddox** [comment]
Hi @Leo-Mahon,
I'm not able to reproduce this issue `Mac: Chrome -v 52.0.2743.116`.
This may be a Chrome `css transition` issue like #37 .

The only way a `toastr` can not be removed is if the `css transition` doesn't work since the `remove` `func` are fired on `transitionend`, try update to the latest version.

**Comment by Leo-Mahon** [comment]
Hey @diegoddox 

I have updated to 3.6.2, the issue persists  but I found out how to reproduce it reliably.

It only happens when you hover the mouse over the area it will appear and then move the mouse away after it pops up.

Can you reproduce it by doing that?

**Comment by diegoddox** [comment]
@Leo-Mahon no, still not able!

![untitled2](https://cloud.githubusercontent.com/assets/2768497/17865499/18075290-68a3-11e6-840f-f322b0644274.gif)

**Comment by Leo-Mahon** [comment]
You need to put a delay between clicking the button and the toastr appearing because the mouse has to be in the area the toaster will appear _before_ it does appear.

Good idea with making a gif btw :)

**Comment by diegoddox** [comment]
Still not able.

![untitled](https://cloud.githubusercontent.com/assets/2768497/17889874/b78fcc18-6932-11e6-8cad-d1b8b849b954.gif)

![untitled2](https://cloud.githubusercontent.com/assets/2768497/17889880/be792cc2-6932-11e6-9ea8-ca6e0f779ff3.gif)

**Comment by Leo-Mahon** [comment]
Well I can't seem to reproduce it either now. I'm a little wary of bugs that just go away but I'l let you know if it reappears or I work out what is going on.

**Comment by diegoddox** [comment]
I will close but fill free to re-open.

**Comment by rafal-p** [comment]
I have the same issue in IE 11
My versions
    "react": "^15.2.0",
    "redux": "^3.5.2",
    "react-redux": "^4.4.5",
    "react-redux-toastr": "^3.4.0",

Can you please reopen?

**Comment by diegoddox** [comment]
@rafal-p can u please upgrade to the lasted?

**Comment by dp-huang** [comment]
I got the same issue, but found there is an option "removeOnHover" that can enable/disable the toastr removal after timeout. Thanks, well designed.

**Comment by diegoddox** [comment]
@dp-huang you can disable the timeout by adding the `timeOut: 0`  in your `toastr` option

**Comment by JFGHT** [comment]
This is happening to me only when I set the timeOut as an option.

**Comment by ashfaqrafi** [comment]
what should I change here to set timeOut to never
`<ReduxToastr
            timeOut={4000}
            newestOnTop={false}
            preventDuplicates
            position="top-right"
            transitionIn="fadeIn"
            transitionOut="fadeOut"
          />`

**Comment by diegoddox** [comment]
@ashfaqrafi  `timeOut={0}`
