### ISSUE TITLE
toastr.confirm actions are not working on IE11 and MS Edge

### ISSUE THREAD

**Issue by gslisboa** [diegoddox/react-redux-toastr#45]

**Comment by JamesPortelli** [comment]
Hi @diegoddox, any idea on a timeframe for fix for this bug?

Thanks
James

**Comment by diegoddox** [comment]
I will first take a look on saturday.

**Comment by diegoddox** [comment]
Hi @gregorystoos  and @JamesPortelli ,
`transitionend` is not working, I will see what I can do ASAP.

**Comment by gslisboa** [comment]
Hi @diegoddox, thanks a lot. Please let me know when it's corrected !

**Comment by diegoddox** [comment]
@gregorystoos can u update to the latest and give me a feedback?

**Comment by gslisboa** [comment]
Hi @diegoddox, I'm sorry but it's not working. Checked on IE11 and MsEdge. None of them are responding to the OK and Cancel actions even after update to v 3.6.4

**Comment by diegoddox** [comment]
@gregorystoos have you clear cache?

**Comment by gslisboa** [comment]
yes @diegoddox !

**Comment by diegoddox** [comment]
I was able to reproduce the issue every time but after the lasted the issue is gone!
I will see what I can do another day.

Thanks a lot!

**Comment by gslisboa** [comment]
For info, I'm having a IE 11 on Win7 and an Edge on Win10

**Comment by diegoddox** [comment]
I've test on Edge and IE11 on Win10.

**Comment by gslisboa** [comment]
I'm using the VMs that you can find here for Virtual box : https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by diegoddox** [comment]
@gregorystoos I'm on a `mac-bootcamp` but it should not be the case, I will try again letter on.

**Comment by gslisboa** [comment]
Hi @diegoddox, could you check more about this issue ?

**Comment by diegoddox** [comment]
Yes, I will try with a virtualbox!

**Comment by nicomfe** [comment]
+1 having same issue

**Comment by diegoddox** [comment]
Will take a look at this today, I'm having a hard time trying to reproduce :(

**Comment by nicomfe** [comment]
@diegoddox I was able to reproduce it using **virtual box** and the **IE11-Win 7**  virtual machine from here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by diegoddox** [comment]
I was not able to reproduce with the new version only with the old.
New version:
![untitled1](https://cloud.githubusercontent.com/assets/2768497/18759221/c4f74418-80fb-11e6-9c3c-548afd661fda.gif)

Old version:
![untitled2](https://cloud.githubusercontent.com/assets/2768497/18759229/d26e812e-80fb-11e6-9af2-1d808e46384a.gif)

and was with this vb: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by diegoddox** [comment]
I've release a new v with only the `click` props, not sure if will work but please update and let me know.

**Comment by nicomfe** [comment]
just tested it and it works, thanks man

**Comment by gslisboa** [comment]
Works here also !!! Thanks @diegoddox you rock ;)
