### ISSUE TITLE
Icon prefix

### ISSUE THREAD

**Issue by petrleocompel** [diegoddox/react-redux-toastr#46]
You souhould provide prefix to toaster icons..

```
[data-icon]:before 
....
[class^="icon-"]:before,
[class*=" icon-"]:before
```

This is too bad. Also "!important" is not good to use.

**Comment by diegoddox** [comment]
@petrleocompel thanks.

**Comment by petrleocompel** [comment]
I would recommend to use some less variable with default :blush: so everybody could change it how need it. Also in code where you are using it (simply extend your component and override some property)

**Comment by diegoddox** [comment]
@petrleocompel thanks, I don't think is necessary:
`use some less variable with default :blush: so everybody could change it how need i` 
but feel free to implement if you want.

**Comment by diegoddox** [comment]
#50
