### ISSUE TITLE
Toastr confirm Message with React Component

### ISSUE THREAD

**Issue by fenos** [diegoddox/react-redux-toastr#48]
Hi, Thanks for the great library,
In the application i'm working on, we have internationalisation in place using [react-intl](https://github.com/yahoo/react-intl), So every text in our app we use the `<FormattedMessage />` component.

So this is what i'm doing to show a `confirmation message`:

``` js
toastr.confirm(
  <FormattedMessage
     id="app.are_u_sure"
     defaultMessage="Are u sure?"
  />, {
   onOk: () => fn(app.id),
   onCancel: () => {},
});
```

But this is how it show on the screen:
<img width="369" alt="screen shot 2016-09-15 at 09 31 27" src="https://cloud.githubusercontent.com/assets/4754064/18543636/abe41164-7b28-11e6-9f01-8461ac6cf15d.png">

Would it be possible to allow to render `React` component as a message, maybe i'm missing something?

**Comment by diegoddox** [comment]
You should be able to pass a `component` #47, what is your current version?
