### ISSUE TITLE
showCloseBotton instead of showCloseButton

### ISSUE THREAD

**Issue by JamesPortelli** [diegoddox/react-redux-toastr#51]
Hi @diegoddox,

Just having a look at the new functionality, noticed that there is a spelling mistake with the prop showCloseBotton which should be showCloseButton instead.

James

**Comment by JamesPortelli** [comment]
Closed by mistake. @diegoddox I have another troubling issue with the closeButton. In the ToastrBox code you do this:
`{options.showCloseBotton && <button className="close-toastr" onClick={this.handleClick.bind(this)}>x</button>}`

Due to the button tag in html implicitly being defaulted to type: 'submit' its causing big issues when I click on it as it tries to submit to the server.

Can you please put the type tag on like so:
`{options.showCloseBotton && <button className="close-toastr" type="button" onClick={this.handleClick.bind(this)}>x</button>}`

**Comment by diegoddox** [comment]
Thanks a lot will fix ASAP

**Comment by diegoddox** [comment]
done!
