### ISSUE TITLE
Demo site differs

### ISSUE THREAD

**Issue by elawad** [diegoddox/react-redux-toastr#52]
I noticed on the demo site, a toast is clickable and disappears instantly when clicked on anywhere.
Running the app locally, you lose the "pointer cursor" and toasts no longer disappears upon click.

**Comment by diegoddox** [comment]
Hi @elawad ,
Sorry but the demo is not updated

**Comment by elawad** [comment]
Oh, I assumed the other way around; that the source has not been updated. 
No worries, thanks.
