### ISSUE TITLE
How do you close an existing Toast manually / limit number of toasts on Screen?

### ISSUE THREAD

**Issue by danielstern** [diegoddox/react-redux-toastr#53]
How do you close an existing Toast manually / limit number of toasts on Screen?

Setting `limit` as a prop or in options doesn't seem to work.

Ideally, I would like to close all the toasts on a page manually, before creating a new one, manually.

**Comment by diegoddox** [comment]
You can use the `clean` method this will remove all toastrs you have on the screen.
ex:

```
import {toastr} from 'react-redux-toastr'
toastr.clean();
```

No, there is no support for limit.
