### ISSUE TITLE
Error fonts load css in webpack

### ISSUE THREAD

**Issue by carloscuatin** [diegoddox/react-redux-toastr#54]
## SASS

![Image](http://image.prntscr.com/image/2886e376e2a646279a3d9c25e4895b17.png)
## ERROR

![Image2](http://image.prntscr.com/image/73e897f499234d2f98ca94495e35c69a.png)

**Comment by diegoddox** [comment]
This is because the fonts are not in the css folder, import from the src instead.
`import 'react-redux-toastr/src/less/index.less'`

**Comment by carloscuatin** [comment]
then I have to get the sources used and put them in my css folder would not believe it would be better than css or less recognize them alone ??

**Comment by diegoddox** [comment]
You're using webpack, it will be very easy to add the less-loader! up to you

**Comment by carloscuatin** [comment]
Yes, Nice 🎉 Thank You

**Comment by diegoddox** [comment]
You're welcome. [less-loader](https://github.com/webpack/less-loader)

**Comment by carloscuatin** [comment]
I sass-loader use that load the CSS file

**Comment by diegoddox** [comment]
what u mean?
