### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by FDiskas** [diegoddox/react-redux-toastr#55]
Missing some fancy features like progressbar displaying then the message will be autoclosed
For more useful settings please check this demo
http://codeseven.github.io/toastr/demo.html

Please add all features from that example :100:

**Comment by pjarmalavicius** [comment]
#68

**Comment by FDiskas** [comment]
:snail: Waiting :)

**Comment by mbifulco** [comment]
Very interested in this PR - would love to see it go through!
