### ISSUE TITLE
Redux dev component overshadows toastrs in examples

### ISSUE THREAD

**Issue by williamboman** [diegoddox/react-redux-toastr#58]
z-index on the redux dev tool component is too damn high

**Comment by diegoddox** [comment]
I know :D, maybe I can add an check that if you're `hot` mode we will override the `devtools` `z-index`

**Comment by williamboman** [comment]
Maybe position toastrs to top-left instead, would be easiest?

**Comment by diegoddox** [comment]
or you can move the `devtools` into other position.
