### ISSUE TITLE
Question and possible issue with toastr insertion point

### ISSUE THREAD

**Issue by jmsherry** [diegoddox/react-redux-toastr#59]
Hi there,
I'm just getting to grips with the full react-redux ecosystem. I've inserted the toastr as suggested and I see the actions dispatched and they are present in the store but no toasts appear.

I can see that the html for the toast is inserted into the page, but it's never populated with text and animated.

The only thing I can think of is that it's something to do with insertion. I have an I18N wrapper and so I've had to insert it like this:

```
  return (
    <Provider store={props.store}>
      <IntlWrapper>
        <div>
          <Router history={browserHistory}>
            {content}
          </Router>
          <ReduxToastr
            timeOut={4000}
            newestOnTop={false}
            position="top-left"
          />
        </div>
      </IntlWrapper>
    </Provider>
  );
```

...could that have anything to do with it??

**Comment by diegoddox** [comment]
It looks fine, have you add or import the styles?

**Comment by jmsherry** [comment]
@diegoddox Sorry, I imported them but then deleted them. Closing issue.
