### ISSUE TITLE
Demo is not working for the bottom position.

### ISSUE THREAD

**Issue by jaebong-human** [diegoddox/react-redux-toastr#6]
I cloned this project and ran 'npm start' like below.

git clone https://github.com/diegoddox/react-redux-toastr.git
cd react-redux-toastr/demo/
npm install
npm start

It was working well for the default position but not for the bottom position.
![top-right](https://cloud.githubusercontent.com/assets/725287/13228679/96b074c0-d9e0-11e5-8997-675c225e230b.png)

All panels were under the screen.
while http://diegoddox.github.io/react-redux-toastr is working.
I thought css files are something wrong.
maybe am I need bootstrap?

![bottom-right](https://cloud.githubusercontent.com/assets/725287/13228680/96be43fc-d9e0-11e5-88f2-d434783ad021.png)

**Comment by diegoddox** [comment]
Thanks for reporting! no you don't need a  bootstrap.
fixed in the same version 2.0.1.
