### ISSUE TITLE
@connect decorator

### ISSUE THREAD

**Issue by kwent** [diegoddox/react-redux-toastr#60]
Hi,

Could we just get rid of this decorator https://github.com/diegoddox/react-redux-toastr/blob/master/src/ReduxToastr.js#L10 and replace by the usual way ?

Decorators are no more supported by `babel6` and using `babel-plugin-transform-decorators-legacy` is adding some more configuration complexity. (And do not work in my app for some reasons...)

Regards,

**Comment by diegoddox** [comment]
That's fine with me, you're welcome to give me a hand ;)
