### ISSUE TITLE
Message should be word-warp

### ISSUE THREAD

**Issue by nthienan** [diegoddox/react-redux-toastr#62]
Any idea how to workarround to add word-warp text in message div? I cannot modify css because it is imported directly.  I think `message` css class should support `word-wrap: break-word` attribute original.

![image](https://cloud.githubusercontent.com/assets/10244759/19625243/3f04c696-993d-11e6-8c79-cf6e0b2ea9fe.png)

My problem as bellow picture:

![image](https://cloud.githubusercontent.com/assets/10244759/19625271/28557502-993e-11e6-8f7b-3d717da1e321.png)

**Comment by diegoddox** [comment]
The `message` `style` is not important and I think we should handle this by adding `break-word`

**Comment by nthienan** [comment]
I also think so. But do you have any suggestions to workaround? As I mentioned I cannot modify style directly.

**Comment by diegoddox** [comment]
Sorry I don't.

**Comment by diegoddox** [comment]
I will close this issue fro now!

**Comment by venuverse** [comment]
any updates on this issue? I think the way it's closed is not right

**Comment by diegoddox** [comment]
Hi @Venugopal46, unfortunately, we're not going to fix this issue since the fix for it will cause other issues, that's why we've closed it.
