### ISSUE TITLE
Cannot import actions constants

### ISSUE THREAD

**Issue by scyros** [diegoddox/react-redux-toastr#63]
I want to catch the action type of the toaster to check it and take some runtime decisions.

¿How can i import them directly?
¿Can i do this?

```
import {REACT_REDUX_TOASTER_ACTION_TYPES_OR_WHATELSE as toasterActionTypes } from 'react-redux-toaster'
```

**Comment by diegoddox** [comment]
try `import {ADD_TOASTR} from 'react-redux-toastr/constants'`
