### ISSUE TITLE
unknown prop 'remove' warning

### ISSUE THREAD

**Issue by HenrikBechmann** [diegoddox/react-redux-toastr#64]
I'm getting 

```
Warning: Unknown prop `remove` on <div> tag. Remove this prop from the element.
...
in div (created by ToastrBox)
```

using react 15.3.2

when invoking this code:

```
        let url = this._getShareUrl()
        let toastrOptions = {
            component: (
                <div>
                <input value = {url} readOnly />
                </div>
            )
        }
        toastr.message('Share charts',toastrOptions)

```

Any ideas how to resolve this?

the message refers me to this: https://facebook.github.io/react/warnings/unknown-prop.html

Re: toastr: nice module!!

**Comment by diegoddox** [comment]
This is because we are parsing the `remove` props to the `div`, Will fix that ASAP

**Comment by diegoddox** [comment]
Please update to the latest and let me know.

**Comment by diegoddox** [comment]
I will close as I'm sure that the new version does't pass the `remove` as `props` to the `div` https://github.com/diegoddox/react-redux-toastr/blob/master/src/ToastrBox.js#L162
