### ISSUE TITLE
Add preventDuplicates option

### ISSUE THREAD

**Issue by jakeorr** [diegoddox/react-redux-toastr#66]
Hi Diego,

Would it be possible to add support for a `preventDuplicates` option similar to what the base toastr module provides?

https://github.com/CodeSeven/toastr#prevent-duplicates

**Comment by diegoddox** [comment]
sure!

**Comment by diegoddox** [comment]
done!

**Comment by jakeorr** [comment]
Excellent, thanks for the update! :)

**Comment by diegoddox** [comment]
you're welcome!
