### ISSUE TITLE
Notification upper again when location change

### ISSUE THREAD

**Issue by anatoliykot** [diegoddox/react-redux-toastr#67]
fix is listen for LOCATION_CHANGE and clear toastr, but I'm sure when this is correct 

(function used in redux-saga)

`function* watchLocationChange() {`
`  while (true) {`
`    try {`
`      yield take(LOCATION_CHANGE);`
`      toastr.clean();`
`    } catch (e) {`
`      log.error(e);`
`    }`
`  }`
`}`

**Comment by diegoddox** [comment]
I'm not sure what you're trying to say!

**Comment by diegoddox** [comment]
any news on this issue?

**Comment by diegoddox** [comment]
I will close but fill free to re-open in case you need.
