### ISSUE TITLE
cannot pass className/id properties to ReduxToastr component

### ISSUE THREAD

**Issue by cdxOo** [diegoddox/react-redux-toastr#69]
As of v3.9.1 neither `<ReduxToastr id="some-id">`  nor `<ReduxToastr className="some-class">` seem to work. It would be nice if one could use the default css of toastrjs that expects the container element to have the ID "toast-container" without manually fiddling around. Also some commercial templates expect that ID as well.

**Comment by diegoddox** [comment]
Hi, now you can use the `props` `className`
