### ISSUE TITLE
How can I set timeout for message ?

### ISSUE THREAD

**Issue by woonmayer** [diegoddox/react-redux-toastr#7]
Hi, It prevents to set timeout for message.

Is there any chance to set it like other types?

Thank you.

**Comment by jaebong-human** [comment]
+1

**Comment by diegoddox** [comment]
No, there is no timeout for `message`, but on the next version you will be able to add a `timeout` to the `message` `options`.

**Comment by jaebong-human** [comment]
Is there any reason not to set timeout for `message`?

```
if (toastr.type !== 'message') {
    this._setIntervalId(setTimeout(this._removeToastr, time));
}
```

**Comment by diegoddox** [comment]
As I had written in the README the `message` is only to be used in case of a large amount of information! I don't see this method as a normal toastr

I'm not planning to change the default behavior as I mention above it is possible to add a `timeout` on the `message` `options`

**Comment by diegoddox** [comment]
EDIT:
When I created the `message` method my view was that if I display a large amount of info to the user he needs to get a chance to read everything without worry if the box will disappear.
