### ISSUE TITLE
Confirm Toast - Both options can be clicked

### ISSUE THREAD

**Issue by cmj91uk** [diegoddox/react-redux-toastr#70]
Using the confirm toast it is possible to click both the OK and Cancel buttons if the clicks are completed before the animations. In this case both the onOk and onCancel fucntions passed as part of the options can be executed.

The issue can be replicated on the demo site (http://diegoddox.github.io/react-redux-toastr/) by leaving the console open. Would it be possible to disable the buttons when one is clicked?

**Comment by diegoddox** [comment]
fixed!
