### ISSUE TITLE
Warning in v.4.0.2

### ISSUE THREAD

**Issue by n0ne** [diegoddox/react-redux-toastr#71]
I've just updated to 4.0.2 and in console this warning:

     Warning: Unknown prop `fit` on <svg> tag. Remove this prop from the element. For details, see      https://fb.me/react-unknown-prop
          in svg (created by Icon)
          in Icon (created by ToastrBox)
          in div (created by ToastrBox)
          in div (created by ToastrBox)
          in div (created by ToastrBox)
          in div (created by ToastrBox)
          in ToastrBox (created by ReduxToastr)
          in div (created by ReduxToastr)
          in ReduxToastr (created by Connect(ReduxToastr))

**Comment by diegoddox** [comment]
done!

**Comment by n0ne** [comment]
Thank you! Awesome!
