### ISSUE TITLE
breaking changes?

### ISSUE THREAD

**Issue by manuxio** [diegoddox/react-redux-toastr#72]
Has the latest release some breaking changes?
I see success/warning/... methods no longer exposed by the library...
Is the doc in readme outdated?

Thanks

**Comment by diegoddox** [comment]
It has some changes but those methods still there.

**Comment by manuxio** [comment]
There's something weird in my setup (freshly updated...)
Gotta investigate... sorry to bother...

Right now I don't see any of those... 
All I see is:

`
add
clean
hideConfirm
remove
showConfirm
`

which, btw, is what's exposed by react-redux-toastr/src/actions.js

**Comment by diegoddox** [comment]
Sorry, I see what you mean now, just use the add function.

```
add({
 title: 'your title',
 message: 'message',
 options: {}
});
```

**Comment by manuxio** [comment]
Yes, I supposed so... 
but then: 
How to confirm? warn? ... can you point me to the correct options?
All I am getting is blank (empty) popups....

**Comment by diegoddox** [comment]
just add a `type` in your object.

```
add({
 type: 'success',
 title: 'your title',
 message: 'message',
 options: {}
});
```

**Comment by manuxio** [comment]
Fantastic ;)
Btw, there's something with the svg...

warning.js:36 Warning: Unknown prop `fit` on <svg> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

**Comment by diegoddox** [comment]
This is fix #71

**Comment by manuxio** [comment]
Strange I didn't get that patch...
let me re-update :)

**Comment by manuxio** [comment]
Great, everything working now...
Can I PM you somehow?

**Comment by diegoddox** [comment]
sorry what you mean by PM? :D

**Comment by manuxio** [comment]
I wanted to send you a private message - don't know how to do it via github...

**Comment by diegoddox** [comment]
diegoddox@hotmail.com
