### ISSUE TITLE
Clicking X on toastr then moving mouse out of and back onto toastr cancels the X click

### ISSUE THREAD

**Issue by torkjels** [diegoddox/react-redux-toastr#76]
If I click on the X to remove the toastr and then quickly move my mouse out of the toastr and quickly back onto the toastr before it has disappeared, the toastr will stay there. This happens regardless of me setting removeOnHover to true or false.

**Comment by diegoddox** [comment]
This is because the `mouseenter`, in case the user `mouseneter` we keep the `toastr` .

**Comment by torkjels** [comment]
So you're saying this is intended functionality even when the user has explicitly pressed X to close the toastr? To me it seems like a bug

**Comment by diegoddox** [comment]
Will take a look.
