### ISSUE TITLE
still getting "Unknown prop 'remove'

### ISSUE THREAD

**Issue by HenrikBechmann** [diegoddox/react-redux-toastr#79]
still getting 

```
Warning: Unknown prop `remove` on <div> tag. Remove this prop from the element.

```
when rendering options.component

version 4.03

**Comment by diegoddox** [comment]
How are you passing the `component`? can you provide a small example of the code?

**Comment by HenrikBechmann** [comment]
```
            let url = json.data.url

            let toastrComponent = ( <div style={{width:"300px"}}>
                    <p style={{width:"290px"}}>To share the selected row of charts, copy the url below, and send it to a friend.</p>
                    <input 
                        ref = {node => {
                            this._inputfieldref = node
                        }}
                        onFocus= {this._inputonfocus}
                        style={{width:"290px"}} value = {url} readOnly />
                    </div> )

            let toastrOptions = {
                icon: (<FontIcon
                    className="material-icons"
                    >

                    share

                </FontIcon>),

                component: toastrComponent
            }
            console.log('toastroptions',toastrOptions,toastr)
            toastr.message('Share charts',toastrOptions)

```

**Comment by diegoddox** [comment]
I'm not able to reproduce, I've update the project but still nothing.
[Here]() you can see that we only pass the props to the component but not to the `html` `element`.

I can be because of the way you're building your dev/pro code?

**Comment by HenrikBechmann** [comment]
Do these images help?

The error:

<img width = "377" alt = "2016-12-03 04 43 09 pm" src="https://cloud.githubusercontent.com/assets/4584381/20867008/ead8c760-ba08-11e6-9a26-9adbcd63b1bb.png" />

The rendered toastr.message...:

<img width="377" alt="2016-12-03 04 39 25 pm" src="https://cloud.githubusercontent.com/assets/4584381/20867014/f74c3f22-ba08-11e6-8898-8f3b9c6c2c28.png" />


The react console view:

<img width="377" alt="2016-12-03 04 39 42 pm" src="https://cloud.githubusercontent.com/assets/4584381/20867017/ff34a864-ba08-11e6-97b4-3c3053cb8165.png" />

The source code:

<img width="1093" alt="2016-12-03 04 42 04 pm" src="https://cloud.githubusercontent.com/assets/4584381/20867018/06551d68-ba09-11e6-8257-2aa9562d93e9.png" />

- Henrik

**Comment by diegoddox** [comment]
Not able to see the images :D

**Comment by HenrikBechmann** [comment]
Sorry, I've uploaded them now (I had just replied to email); I can't get them to render inline

**Comment by diegoddox** [comment]
Can you try like this ex:
```
let toastrComponent = () => ( <div style={{width:"300px"}}> ....
```

**Comment by HenrikBechmann** [comment]
@diegoddox That worked! (cleared the warning). Subtle. Thanks!

What's up with that? function return of jsx expression creates react component; jsx expression return of jsx doesn't?

**Comment by diegoddox** [comment]
Jep, you're retuning a `func`.
