### ISSUE TITLE
Bug icon on error toast is not appropriate

### ISSUE THREAD

**Issue by benbarber** [diegoddox/react-redux-toastr#81]
I feel that the bug icon is not appropriate for an error message as it give's the wrong message to the user.
 
Presenting the user with an error toast doesn't always indicate that there is a bug, it could be that they don't have permission, or have input some data incorrectly in a form.

**Comment by Toyinster** [comment]
+1  I would prefer it if we were able to opt out of the icons.

**Comment by diegoddox** [comment]
@BenBarber I've change the `error` `icon`.
@Toyinster you can pass your own icon if you prefer
ex:
```
const toastrOptions = {
 icon: (<div className="icon-my-custom-icon" />)
};

toastr.success('The message', toastrOptions);
```

**Comment by Toyinster** [comment]
That was ultra quick - thanks for the response. I like the new features, but would like to opt out of the icons completely...is that possible without getting a blank space where the icon would normally be?

**Comment by benbarber** [comment]
@diegoddox Icon change is perfect, thanks for the quick response!
