### ISSUE TITLE
Unexpected Token Error ReduxToastr.js

### ISSUE THREAD

**Issue by abarcemas** [diegoddox/react-redux-toastr#85]
I npm install this package and when I get to step 3, (declaring the `import { reducer as toastrReducer } from 'react-redux-toastr'` I get this error.

```
ERROR in ./~/react-redux-toastr/src/ReduxToastr.js
Module parse failed: c:\www\react-boilerplate\node_modules\react-redux-toastr\src\ReduxToastr.js Unexpected token (12:21)
You may need an appropriate loader to handle this file type.
|
| class ReduxToastr extends Component {
|   static displayName = 'ReduxToastr';
|
|   static propTypes = {
 @ ./~/react-redux-toastr/src/index.js 1:0-40
 @ ./app/reducers.js
 @ ./app/store.js
 @ ./app/app.js
 @ multi main

ERROR in ./~/react-redux-toastr/src/reducer.js
Module parse failed: c:\www\react-boilerplate\node_modules\react-redux-toastr\src\reducer.js Unexpected token (30:8)
You may need an appropriate loader to handle this file type.
|     if (!config.newestOnTop) {
|       newState = {
|         ...state,
|         toastrs: [
|           ...state.toastrs,
 @ ./~/react-redux-toastr/src/index.js 3:0-43
 @ ./app/reducers.js
 @ ./app/store.js
 @ ./app/app.js
 @ multi main
```

I'm using https://github.com/mxstbr/react-boilerplate.

**Comment by dcmdestello** [comment]
Same problem here, using `mxstbr/react-boilerplate` v.3.2.1 with my app on top of it. For now I've solved this issue by manually moving the `react-redux-toastr/` folder out of `node_modules/` to my own `lib/` folder.

So my imports look like this:

`import { reducer as toastrReducer } from 'lib/react-redux-toastr';`

It's probably a missconfiguration within the react-boilerplate's webpack but I wonder what is it about this npm package that makes it incompatible.

**Comment by diegoddox** [comment]
I will take a look

**Comment by diegoddox** [comment]
This is because of the way they have setup webpack config file

**Comment by dcmdestello** [comment]
Any idea as to why? I've only encountered this issue with this package so far.

**Comment by diegoddox** [comment]
Have u read my comment above? You should open an issue with then, some of the code I wrote in es7 they are not handling, that's why you're getting this error.

**Comment by likesalmon** [comment]
@dcmdestello 

react-redux-toastr is written with ES7 features and must be processed by Babel. The default webpack configuration excludes the entire `node_modules/` directory, but you can override that for specific modules like this:

*internals/webpack/webpack.base.babel.js, line ~18*
```javascript
module: {
    loaders: [
      {
        test: /\.js$/, // Transform all .js files required somewhere with Babel
        loader: 'babel-loader',
        // Exclude node_modules from babel processing except react-redux-toastr,
        // which is written in ES7.
        // Add more modules like:
        // /node_modules\/(?!(react-redux-toastr|my-other-module)\/).*/
        exclude: /node_modules\/(?!(react-redux-toastr)\/).*/,
        query: options.babelQuery,
      },
```

Check out [this thread](https://github.com/webpack/webpack/issues/2031) for several alternative solutions. I'm fond of [this one](https://github.com/webpack/webpack/issues/2031#issuecomment-219040479).

**Comment by amorris-apex** [comment]
@dcmdestello one more thing:

In **webpack.base.babel** you need to swap `main` and `jsnext:main` in the `resolve.mainFields` array like this:

`mainFields: ['browser', 'main', 'jsnext:main'],`

See [this answer](https://github.com/react-boilerplate/react-boilerplate/issues/1569#issuecomment-280223836).
