### ISSUE TITLE
Hide a specific toast?

### ISSUE THREAD

**Issue by aaronbeall** [diegoddox/react-redux-toastr#86]
I see you can hide all toasts using `toastr.clean()` but is there a way to hide a specific toast or toast type?

**Comment by diegoddox** [comment]
Sorry but no, I'll implement asap

**Comment by aaronbeall** [comment]
No rush but it would be nice. :) If I have time I can look into creating a PR. Another option is if there was a way to acquire the toast id, perhaps the `toastr` methods could return the id for the next toast, then I could just dispatch a `toast/remove` action myself.

**Comment by diegoddox** [comment]
This `func` is already in use but is not public for the `emitter` so it should not take that long to implement.

**Comment by diegoddox** [comment]
But if you should be able to remove `toastrs` by `id` that means you need have the ability to self add the `toastr` `id` which is not possible today

**Comment by diegoddox** [comment]
You can at least remove by type with the latest version, not sure if will be necessary to remove a `toastr` by `id` as you have access to this in the `toastr` `component` `options`
