### ISSUE TITLE
scss import

### ISSUE THREAD

**Issue by manuxio** [diegoddox/react-redux-toastr#87]
for some reason, when including this repo in a wider project, the scss import fails...
I have no clue why, but the issue is fixed with:

@import './animation.scss';
@import './confirm.scss';

instead of

@import './animation';
@import './confirm;

Please change this in a future release...
Thank you

**Comment by diegoddox** [comment]
well this may be your project that has to handle, else I don't know what you're talking about.

**Comment by manuxio** [comment]
Be it my project or the syntax itself, when using a complex configuration (with tweaks and stuff) not adding the extensions is a problem.
You can fix it easily, just by adding the '.scss'...
if that's not possible, then I'll figure it out by myself.
The issue is certainly related with sass-loader ... nevertheless, it should not be a big issue to just add the extensions...

**Comment by diegoddox** [comment]
[done](https://github.com/diegoddox/react-redux-toastr/blob/master/src/styles/index.scss#L1)
